const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),{PGlite}=require('@electric-sql/pglite');const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('contract lifecycle isolates parties, prevents stale changes, freezes signed originals and makes retries idempotent',async()=>{const db=new PGlite();try{
await db.exec(`create role anon;create role authenticated;create role service_role;create schema omg_private;
create function omg_private.token_hash(uuid) returns text language sql as 'select $1::text';
create table properties(id uuid primary key,business_id uuid,name text);
create table owners(id uuid primary key,active boolean);
create table owner_sessions(owner_id uuid,property_id uuid,login_token_hash text,token_expires_at timestamptz);
create table employees(id uuid primary key,property_id uuid,role text,active boolean,display_name text,job_title text,contact_phone text,scheduled_clock_in time,scheduled_clock_out time);
create table work_sessions(employee_id uuid,login_token_hash text,token_expires_at timestamptz,status text);
create table employee_payroll_settings(employee_id uuid,pay_type text,hourly_rate integer,monthly_salary integer,pay_day integer);
create table property_messages(id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,sender_type text,sender_owner_id uuid,sender_employee_id uuid,message text,priority text,message_type text);
create table property_message_recipients(message_id uuid,recipient_key text,recipient_type text,employee_id uuid,owner_id uuid);
create function omg_private.can_manage_shared_property(t uuid,p uuid,s text) returns boolean language sql as $$select exists(select 1 from public.owner_sessions where login_token_hash=t::text and property_id=p and token_expires_at>now())$$;
insert into properties values('${id(1)}','${id(9)}','본점'),('${id(2)}','${id(9)}','타지점');insert into owners values('${id(10)}',true),('${id(20)}',true);
insert into owner_sessions values('${id(10)}','${id(1)}','${id(100)}',now()+interval '1h'),('${id(20)}','${id(2)}','${id(200)}',now()+interval '1h');
insert into employees(id,property_id,role,active,display_name) values('${id(11)}','${id(1)}','staff',true,'근무자 A'),('${id(12)}','${id(1)}','staff',true,'근무자 B');
insert into work_sessions values('${id(11)}','${id(110)}',now()+interval '1h','working'),('${id(12)}','${id(120)}',now()+interval '1h','completed');`);
await db.exec(fs.readFileSync('supabase/migrations/20261007170134_employment_contracts.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20261009020502_contract_workflow_v2.sql','utf8'));
await assert.rejects(db.query('select contract_business_info($1,$2)',[id(200),id(1)]),/권한/);
await db.query('select contract_business_info($1,$2,$3,$4)',[id(100),id(1),'save',{business_name:'사업장',employer_name:'사업주',phone:'010',address:'서울'}]);
const rpc=async(action,data={},token=id(100))=>(await db.query('select employment_contract_rpc($1,$2,$3) data',[token,action,data])).rows[0].data;
assert.equal((await rpc('list',{employee_id:id(11)})).defaults.business_info.employer_name,'사업주');
const draft={contract_fields:{kind:'standard',pay_type:'annual',amount:36000000},contract_ready:true,id:id(500),employee_id:id(11),title:'계약서',content:'계약 내용',employer_name:'대표자',version:0};
await assert.rejects(rpc('list',{employee_id:id(11)},id(200)),/권한/);await assert.rejects(rpc('list',{employee_id:id(11)},id(120)),/권한/);
let c=(await rpc('draft',draft)).contract;assert.equal(c.version,1);assert.equal(c.contract_fields.amount,36000000);assert.equal(c.contract_ready,true);
await assert.rejects(rpc('get',{id:c.id},id(200)),/권한/);await assert.rejects(rpc('get',{id:c.id},id(110)),/권한/);
await assert.rejects(rpc('draft',{...draft,version:0}),/변경/);
const signature='data:image/png;base64,'+'A'.repeat(200);
await assert.rejects(rpc('send',{id:c.id,signature,confirmed:true}),/최신/);
c=(await rpc('send',{id:c.id,version:1,signature,confirmed:true})).contract;assert.equal(c.status,'sent');assert.equal(c.content_hash.length,64);
assert.equal((await rpc('send',{id:c.id,version:1,signature,confirmed:true})).duplicate,true);
await assert.rejects(rpc('draft',{...draft,version:1,content:'변조'}),/변경/);
await assert.rejects(rpc('sign',{id:c.id,version:1,content_hash:c.content_hash,signature,confirmed:true},id(120)),/권한/);
await assert.rejects(rpc('sign',{id:c.id,version:1,content_hash:'wrong',signature,confirmed:true},id(110)),/변경/);
assert.ok((await rpc('get',{id:c.id},id(110))).contract.viewed_at);
const signed=await rpc('sign',{id:c.id,version:1,content_hash:c.content_hash,signature,confirmed:true},id(110));assert.equal(signed.contract.status,'signed');
assert.equal((await rpc('sign',{id:c.id},id(110))).duplicate,true);
assert.equal((await db.query('select count(*)::int n from property_messages')).rows[0].n,2);
await assert.rejects(rpc('cancel',{id:c.id}),/취소/);
await assert.rejects(db.query('update employment_contracts set content=$1 where id=$2',['modified',c.id]),/변경/);
await db.query('update employment_contracts set pdf_path=$1 where id=$2',['contract.pdf',c.id]);
await assert.rejects(db.query('delete from employment_contracts where id=$1',[c.id]),/삭제/);
assert.equal((await rpc('list',{},id(110))).contracts.length,1);
await assert.rejects(rpc('template_save',{employee_id:id(11),name:'bad',content:'bad'},id(200)),/권한/);
assert.equal((await db.query("select has_function_privilege('anon','employment_contract_rpc(uuid,text,jsonb)','execute') allowed")).rows[0].allowed,false);
const c2=(await rpc('draft',{...draft,id:id(501)})).contract;await rpc('send',{id:c2.id,version:1,signature,confirmed:true});await rpc('request_change',{id:c2.id,reason:'급여일 수정'},id(110));await assert.rejects(rpc('sign',{id:c2.id,version:1,signature,confirmed:true},id(110)),/변경/);
await db.exec('update owner_sessions set token_expires_at=now()-interval \'1 minute\'');await assert.rejects(rpc('get',{id:c.id}),/만료/);
}finally{await db.close();}});
