// Disposable PostgreSQL tests; no live accounts or external services.
const {PGlite}=require('@electric-sql/pglite');
const {pgcrypto}=require('@electric-sql/pglite/contrib/pgcrypto');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const db=new PGlite({extensions:{pgcrypto}});
let count=0;const check=(v,msg)=>{assert.ok(v,msg);count++;console.log('PASS '+msg);};
async function one(sql,args=[]){return(await db.query(sql,args)).rows[0];}
async function rpc(name,args){await db.exec('set role anon');try{return(await one(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args)).r;}finally{await db.exec('reset role');}}
(async()=>{
 await db.exec(`create role anon;create role authenticated;create role service_role;grant usage on schema public to anon,authenticated;
 create schema auth;create table auth.users(id uuid primary key,email text not null);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select '{}'::jsonb$$;`);
 for(const f of fs.readdirSync(path.join(root,'migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(read('migrations/'+f));

 await db.exec(read('migrations/034_guest_support.sql'));
 await db.exec(read('setup/002_register_employee_pins.example.sql').replace(/PIN_([1-4])/g,'731482'));
 await db.exec(read('setup/007_create_owner.example.sql').replace(/OWNER_LOGIN_ID/g,'boss.test').replace(/OWNER_PIN_6_TO_8/g,'517394'));
 const owner=await rpc('start_owner_session',['boss.test','517394']);
 const staff=(await db.query("select id,property_id from public.employees where active and role<>'owner' order by id")).rows;
 const worker=await rpc('start_work_session',[staff[0].id,'731482']);
 const call=async(action,data={},token=owner.access_token,guest=null)=>(await one('select public.guest_support_rpc($1,$2,$3,$4,$5) r',[action,JSON.stringify(data),token,guest,'a'.repeat(64)])).r;
 const rejected=async(fn,label)=>{await assert.rejects(fn);check(true,label);};
 let cfg=await call('settings');const slug=cfg.config.slug;
 check(!cfg.config.enabled,'new module is opt-in');
 await rejected(()=>call('portal',{slug},null),'disabled portal cannot be opened');
 await call('save_settings',{enabled:true,chat_enabled:true,items:[]});
 const today=new Date().toISOString().slice(0,10),guest=require('node:crypto').randomUUID();
 const start={slug,name:'Test Guest',check_in:today,check_out:today,new_token:guest};
 const room=await call('start',start,null);const id=room.room_id;
 check((await call('start',start,null)).room_id===id,'retried entry creates one room');
 await rejected(()=>call('messages',{room_id:id},null,require('node:crypto').randomUUID()),'invalid guest token rejected');
 await rejected(()=>call('settings',{},null,guest),'guest cannot access settings');
 await rejected(()=>call('save_settings',{enabled:false},worker.access_token),'worker cannot change owner settings');
 const cid=require('node:crypto').randomUUID();
 const sent=await call('send',{room_id:id,client_id:cid,body:'Help'},null,guest);
 check((await call('send',{room_id:id,client_id:cid,body:'Help'},null,guest)).message_id===sent.message_id,'send retry does not duplicate');
 await call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),body:'We can help'},worker.access_token);
 const view=await call('messages',{room_id:id},null,guest);
 check(view.messages[1].sender_name==='직원'&&view.messages[1].sender_key===null,'guest sees staff alias only');
 check(view.room.assigned_name==='직원'&&view.room.assigned_key===null,'assignment identity hidden from guest');
 const internal=await call('messages',{room_id:id});
 check(internal.messages[1].sender_key==='employee:'+staff[0].id,'internal record retains actual sender');
 await rejected(()=>call('claim',{room_id:id}),'another responder cannot silently claim');
 await call('claim',{room_id:id,takeover:true});
 check((await call('messages',{room_id:id},null,guest)).messages.length===2,'internal handover audit hidden from guest');
 const prefs=[{actor_key:'employee:'+staff[0].id,enabled:true,property_ids:[staff[0].property_id],days:[0,1,2,3,4,5,6],start_time:'00:00',end_time:'00:00'}];
 await call('save_preferences',{preferences:prefs});
 const dispatch=async e=>(await one('select public.get_guest_chat_dispatch($1) r',[e])).r;
 check((await dispatch(room.event_id)).priority==='normal','new room notification is normal');
 check((await dispatch(sent.event_id)).priority==='urgent','guest message notification is urgent');
 check((await dispatch(sent.event_id)).recipient_topics[0].endsWith(staff[0].id),'enabled worker receives own branch alert');

 const zone=(await one('select timezone from public.properties where id=$1',[staff[0].property_id])).timezone;
 const clock=await one("select extract(dow from now() at time zone $1)::int dow,((now() at time zone $1)+interval '1 hour')::time::text future,((now() at time zone $1)+interval '2 hours')::time::text later",[zone]);
 await call('save_preferences',{preferences:prefs.map(p=>({...p,days:[(clock.dow+3)%7]}))});
 check((await dispatch(sent.event_id)).recipient_topics.length===0,'excluded weekday suppresses push');
 await call('save_preferences',{preferences:prefs.map(p=>({...p,start_time:clock.future,end_time:clock.later}))});
 check((await dispatch(sent.event_id)).recipient_topics.length===0,'outside notification hours suppresses push');
 await call('save_preferences',{preferences:prefs});
 const photo=await call('upload_begin',{room_id:id,mime:'image/jpeg'},null,guest);
 await rejected(()=>call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),asset_id:photo.asset_id},null,guest),'uncompleted upload cannot be sent');
 await call('upload_finish',{room_id:id,asset_id:photo.asset_id},null,guest);
 await rejected(()=>call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),asset_id:photo.asset_id}),'staff cannot attach another sender pending photo');
 await rejected(()=>call('upload_begin',{room_id:id,mime:'application/pdf'},null,guest),'chat only accepts images');
 await call('save_preferences',{preferences:prefs.map(p=>({...p,enabled:false}))});
 check((await dispatch(sent.event_id)).recipient_topics.length===0,'disabled notifications suppress push but retain access');
 await call('save_settings',{enabled:false,chat_enabled:false,items:[]});
 await rejected(()=>call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),body:'blocked'},null,guest),'disabled module rejects new messages');
 check((await call('messages',{room_id:id})).messages.length===3,'disabling preserves staff history');
 await rejected(()=>rpc('guest_support_rpc',['rooms','{}',owner.access_token,null,'']),'anon cannot bypass Edge gateway');
 const alien=require('node:crypto').randomUUID();
 await db.query("insert into public.properties(id,business_id,code,name) select $1,business_id,'alien','Other property' from public.properties limit 1",[alien]);
 const other=require('node:crypto').randomUUID();
 await db.query("insert into public.guest_chat_rooms(id,property_id,guest_name,check_in,check_out,token_hash,expires_at,ip_hash) values($1,$2,'Other',current_date,current_date,'other',now()+interval '1 day','x')",[other,alien]);
 await rejected(()=>call('messages',{room_id:other}),'unshared branch cannot read guest room');
 await rejected(()=>call('save_preferences',{preferences:prefs.map(p=>({...p,property_ids:[alien]}))}),'unshared branch cannot be selected for alerts');

 // Retention operates on a fixed, platform-authorized preview; never on all tenants.
 const operator=require('node:crypto').randomUUID();
 const storage=async(action,data={})=>(await one('select public.platform_message_storage($1,$2) r',[action,JSON.stringify(data)])).r;
 await rejected(()=>storage('usage'),'storage usage rejects anonymous caller');
 await db.query("insert into auth.users(id,email) values($1,'operator@test.invalid')",[operator]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[operator]);
 await rejected(()=>storage('usage'),'ordinary account cannot access storage');
 await db.query('insert into public.platform_administrators(user_id) values($1)',[operator]);
 const usage=await storage('usage');check(usage.properties.length>=2,'platform usage lists each property separately');
 await rejected(()=>storage('preview',{property_id:staff[0].property_id,months:1,categories:['chat']}),'unsupported retention period rejected');
 await call('save_settings',{enabled:true,chat_enabled:true,items:[]});
 const old=await call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),body:'Old text'});
 await db.query("update public.guest_chat_messages set created_at=now()-interval '7 months' where id=$1",[old.message_id]);
 const attached=await call('upload_begin',{room_id:id,mime:'image/jpeg'});await call('upload_finish',{room_id:id,asset_id:attached.asset_id});
 const photoMessage=await call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),body:'Old photo',asset_id:attached.asset_id});
 await db.query("update public.guest_chat_messages set created_at=now()-interval '7 months' where id=$1",[photoMessage.message_id]);
 await db.query("update public.guest_support_assets set created_at=now()-interval '7 months' where id=$1",[attached.asset_id]);
 const preview=await storage('preview',{property_id:staff[0].property_id,months:6,categories:['chat','chat_photos']});
 check(preview.summary.chat_count===2&&preview.summary.chat_photo_count===1,'preview counts only old content');
 check(!!(await one('select id from public.guest_chat_messages where id=$1',[old.message_id])),'preview does not delete data');
 await rejected(()=>storage('execute',{job_id:preview.job_id,confirm_name:'wrong'}),'wrong property confirmation rejected');
 const job=await storage('execute',{job_id:preview.job_id,confirm_name:preview.summary.property_name});check(job.status==='pending','photo cleanup persists retryable storage queue');
 check(!(await one('select id from public.guest_chat_messages where id=$1',[old.message_id])),'selected old text is removed');
 check(!!(await one('select id from public.guest_chat_messages where id=$1',[sent.message_id])),'recent content retained');
 check(!!(await one('select id from public.guest_chat_rooms where id=$1',[other])),'another property is unaffected');
 await rejected(()=>call('send',{room_id:id,client_id:require('node:crypto').randomUUID(),asset_id:attached.asset_id}),'queued photo cannot be reused');
 check((await storage('execute',{job_id:preview.job_id,confirm_name:preview.summary.property_name})).status==='pending','repeat execute is idempotent');
 const work=async(done=[])=>(await one('select public.platform_message_storage_worker($1,$2,$3) r',[operator,job.job_id,done])).r;
 check((await work()).files[0].object_path===attached.path,'worker only receives persisted property-scoped paths');
 check((await work([attached.asset_id])).status==='complete','completed storage deletion finalizes queued job');
 check((await work([attached.asset_id])).status==='complete','completed worker retry is safe');
 await rejected(()=>one('select public.platform_message_storage_worker($1,$2) r',[staff[0].id,job.job_id]),'storage worker rejects non-platform user');
 console.log(`${count} guest support checks passed`);await db.close();
})().catch(async e=>{console.error(e.message,e.detail||'',e.stack);await db.close();process.exitCode=1;});
