import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {createGuestSupportHandler} from '../functions/guest-support/handler.mjs';
const id='00000000-0000-4000-8000-000000000001';
function setup(options={}){const calls=[];const handle=createGuestSupportHandler({cryptoApi:webcrypto,env:n=>({SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'fake-service',PUSH_ADMIN_SECRET:'fake-secret'})[n],fetcher:async(url,init)=>{const body=typeof init.body==='string'?JSON.parse(init.body):null;calls.push({url,body});if(url.includes('/rpc/')){if(options.deny)return Response.json({code:'P0001',message:'로그인이 필요합니다.'},{status:400});return Response.json(options.value||{ok:true,event_id:id});}if(url.includes('/dispatch-notification'))return Response.json({ok:!options.failPush},{status:options.failPush?502:200});if(url.includes('/object/sign'))return Response.json([{path:'p/a',signedURL:'/object/sign/guest-support/p/a?token=fake'}]);throw Error('unexpected call');}});return {calls,request:(action,data={},other={})=>handle(new Request('https://example.invalid/guest-support',{method:'POST',headers:{'Content-Type':'application/json','x-forwarded-for':'192.0.2.4'},body:JSON.stringify({action,data,...other})}))};}
test('upload_finish cannot be forged by public caller',async()=>{const h=setup();assert.equal((await h.request('upload_finish')).status,400);assert.equal(h.calls.length,0);});
test('database errors are returned without service values',async()=>{const h=setup({deny:true});const r=await h.request('messages',{room_id:id},{guest_token:id});assert.equal(r.status,400);assert.equal((await r.json()).message,'로그인이 필요합니다.');assert.equal(h.calls.length,1);});
test('saved messages remain successful when push needs retry',async()=>{const h=setup({failPush:true});const r=await h.request('send',{room_id:id,body:'Hello',client_id:id},{guest_token:id});const v=await r.json();assert.equal(r.status,200);assert.equal(v.push_state,'pending');});
test('IP is hashed only from server request header',async()=>{const h=setup();await h.request('start',{slug:id,new_token:id,ip:'evil'});const hash=h.calls[0].body.p_ip_hash;assert.match(hash,/^[a-f0-9]{64}$/);assert(!JSON.stringify(h.calls).includes('192.0.2.4'));});
test('only authorized asset paths receive signed URLs',async()=>{const h=setup({value:{ok:true,assets:[{id,path:'p/a',mime:'image/jpeg'}]}});const r=await h.request('messages',{room_id:id},{guest_token:id});const v=await r.json();assert.equal(v.assets[0].path,undefined);assert.equal(v.assets[0].url,'https://example.invalid/storage/v1/object/sign/guest-support/p/a?token=fake');assert.deepEqual(h.calls[1].body.paths,['p/a']);});
