const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert/strict');
const path=require('node:path');process.chdir(path.join(__dirname,'../..'));
const html=fs.readFileSync('messages.html','utf8');const dom=new JSDOM(html.replace(/<script[\s\S]*?<\/script>/g,''),{url:'https://omgworks24.com/messages.html',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
w.HTMLDialogElement.prototype.close=function(){this.removeAttribute("open");};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute("open","");};w.omgTransition={ready(){}};w.omgSession={require:async()=>({accessToken:'x',propertyId:'p',employeeId:'e',sessionKind:'staff'})};
const items=[{message_id:'a',sender_label:'Owner',sender_type:'owner',message_type:'general',message:'Hello',created_at:new Date().toISOString(),priority:'normal'},{message_id:'b',sender_label:'Owner',sender_type:'owner',message_type:'announcement',acknowledged_at:'2026-09-26T10:00:00Z',message:'Notice',created_at:new Date().toISOString(),priority:'normal'}];
w.omgSupabase={rpc:async(name)=>name==='staff_chat_rpc'?({data:{ok:true,rooms:[{peer:'owner:x',name:'Owner',preview:'Hello',updated_at:new Date().toISOString(),unread:1}]}}):({data:{ok:true,can_manage:false,messages:items,recipients:[],unread_count:2}})};
w.GuestSupport={esc:s=>String(s??''),call:async()=>({ok:true,actor:{key:'employee:e'},properties:[{id:'p',name:'Property'}],rooms:[{id:'r',property_name:'Property',guest_name:'Emma',status:'open',room_number:'',updated_at:new Date().toISOString(),unread:1}]})};
w.eval(fs.readFileSync('staff-chat-client.js','utf8'));w.eval(fs.readFileSync('message-hub.js','utf8'));for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(m[1].includes('let session=null'))w.eval(m[1]);}
setTimeout(async()=>{try{assert.equal(w.document.querySelector('[data-hub].active').dataset.hub,'guest');assert.match(w.document.getElementById('guestRooms').textContent,/Emma/);assert.equal(w.document.getElementById('list').hidden,true);w.document.querySelector('[data-hub="staff"]').click();await new Promise(r=>setTimeout(r,30));assert.equal(w.document.querySelector('.mail-tabs').hidden,true);assert.equal(w.document.getElementById('list').hidden,true);assert.match(w.document.getElementById('staffRooms').textContent,/Hello/);assert(!w.document.getElementById('staffRooms').textContent.includes('Notice'));assert.match(w.document.querySelector('#staffRooms a').getAttribute('href'),/staff-chat.html/);w.document.querySelector('[data-hub="alerts"]').click();assert.match(w.document.getElementById('list').textContent,/Notice/);assert(!w.document.getElementById('list').textContent.includes('Hello'));assert.equal(w.document.querySelector('.mail-tabs').hidden,true);assert.equal(w.document.getElementById('composeToggle').hidden,true);w.document.querySelector('.message-card').click();await new Promise(r=>setTimeout(r,20));assert.equal(w.document.getElementById('ack').hidden,true);assert.equal(w.document.getElementById('announcementConfirm').hidden,true);w.document.getElementById('close').click();await new Promise(r=>setTimeout(r,30));w.document.querySelector('[data-hub=staff]').click();await new Promise(r=>setTimeout(r,20));const search=w.document.getElementById('searchToggle');assert.equal(search.closest('.hub-tabs').className,'hub-tabs');assert.equal(w.document.getElementById('messageSearch').hidden,true);search.click();assert.equal(w.document.getElementById('messageSearch').hidden,false);const input=w.document.getElementById('messageSearchInput');input.value='missing';input.dispatchEvent(new w.Event('input'));assert(!w.document.getElementById('staffRooms').textContent.includes('Hello'));input.value='Hello';input.dispatchEvent(new w.Event('input'));assert(w.document.getElementById('staffRooms').textContent.includes('Hello'));w.document.getElementById('searchClear').click();await new Promise(r=>setTimeout(r,30));assert.equal(w.document.getElementById('messageSearch').hidden,true);assert.equal(input.value,'');await w.openDetail({...items[1],acknowledged_at:null});assert.equal(w.document.getElementById('ack').hidden,false);assert.equal(w.document.getElementById('ack').textContent,'이해했음 확인');assert.equal(w.document.getElementById('announcementConfirm').hidden,false);console.log('PASS actual messages page: initial guest pane, guest data, staff/alert separation, navigation');}catch(e){console.error(e);process.exitCode=1;}finally{w.close();}},150);
