const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert/strict');
const path=require('node:path');process.chdir(path.join(__dirname,'../..'));
const html=fs.readFileSync('messages.html','utf8');const dom=new JSDOM(html.replace(/<script[\s\S]*?<\/script>/g,''),{url:'https://omgworks24.com/messages.html',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
w.omgTransition={ready(){}};w.omgSession={require:async()=>({accessToken:'x',propertyId:'p',employeeId:'e',sessionKind:'staff'})};
const items=[{message_id:'a',sender_label:'Owner',sender_type:'owner',message_type:'general',message:'Hello',created_at:new Date().toISOString(),priority:'normal'},{message_id:'b',sender_label:'Owner',sender_type:'owner',message_type:'announcement',message:'Notice',created_at:new Date().toISOString(),priority:'normal'}];
w.omgSupabase={rpc:async()=>({data:{ok:true,can_manage:false,messages:items,recipients:[],unread_count:2}})};
w.GuestSupport={esc:s=>String(s??''),call:async()=>({ok:true,actor:{key:'employee:e'},properties:[{id:'p',name:'Property'}],rooms:[{id:'r',property_name:'Property',guest_name:'Emma',status:'open',room_number:'',updated_at:new Date().toISOString(),unread:1}]})};
w.eval(fs.readFileSync('message-hub.js','utf8'));for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(m[1].includes('let session=null'))w.eval(m[1]);}
setTimeout(()=>{try{assert.equal(w.document.querySelector('[data-hub].active').dataset.hub,'guest');assert.match(w.document.getElementById('guestRooms').textContent,/Emma/);assert.equal(w.document.getElementById('list').hidden,true);w.document.querySelector('[data-hub="staff"]').click();assert.match(w.document.getElementById('list').textContent,/Hello/);assert(!w.document.getElementById('list').textContent.includes('Notice'));w.document.querySelector('[data-hub="alerts"]').click();assert.match(w.document.getElementById('list').textContent,/Notice/);assert(!w.document.getElementById('list').textContent.includes('Hello'));assert.equal(w.document.querySelector('.mail-tabs').hidden,false);console.log('PASS actual messages page: initial guest pane, guest data, staff/alert separation, navigation');}catch(e){console.error(e);process.exitCode=1;}finally{w.close();}},150);
