export function createContractPdfRenderer({PDFDocument,fontkit,rgb,fetcher=fetch}){
 let fontPromise;
 const fontBytes=()=>fontPromise||(fontPromise=fetcher('https://cdn.jsdelivr.net/gh/google/fonts@16680f8688ffcd467d2eb2146a9ce0343404581d/ofl/nanumgothic/NanumGothic-Regular.ttf',{signal:AbortSignal.timeout(15000)}).then(async r=>{if(!r.ok)throw Error('계약서 글꼴을 불러오지 못했습니다. 다시 시도해주세요.');return new Uint8Array(await r.arrayBuffer());}).catch(e=>{fontPromise=null;throw e;}));
 async function setup(){const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const font=await pdf.embedFont(await fontBytes(),{subset:false});return{pdf,font};}
 async function validate(contract,signature){const{pdf,font}=await setup(),supported=new Set(font.getCharacterSet());const text=[contract.title,contract.content,contract.employer_name,contract.employee_name,contract.property_name].join('\n');const missing=[...new Set([...text].filter(c=>!['\n','\r','\t'].includes(c)&&!supported.has(c.codePointAt(0))))];if(missing.length)throw Error('PDF에서 지원하지 않는 문자를 바꿔주세요: '+missing.slice(0,12).join(' '));if(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(signature||'')||signature.length>200000)throw Error('서명을 다시 입력해주세요.');const image=await pdf.embedPng(signature);if(image.width<100||image.height<40||image.width>1600||image.height>800)throw Error('서명 크기가 올바르지 않습니다.');}
 function parse(content,title){const result=[],lead=[];let current=null;for(const raw of String(content||'').split(/\r?\n/)){const line=raw.trim();if(!line)continue;if(line===String(title||'').trim()&&!result.length&&!lead.length)continue;const hit=line.match(/^(\d+)\.\s*(.+)$/);if(hit){current={number:hit[1],title:hit[2],lines:[]};result.push(current);}else if(current)current.lines.push(line);else lead.push(line);}return{lead,groups:result};}
 async function render(c){
  const{pdf,font}=await setup();pdf.setTitle(c.title);pdf.setAuthor(c.employer_name||c.property_name||'');pdf.setSubject('근로계약서');pdf.setCreationDate(new Date(c.signed_at));pdf.setModificationDate(new Date(c.signed_at));
  let page,y;const navy=rgb(.094,.192,.325),gray=rgb(.40,.46,.55),border=rgb(.84,.88,.92),soft=rgb(.94,.965,.99),margin=48,width=499,contentRight=margin+width,widths=new Map();
  const charWidth=(ch,size)=>{const key=ch+'|'+size;if(!widths.has(key))widths.set(key,font.widthOfTextAtSize(ch,size));return widths.get(key);};
  function wrap(text,size,maxWidth){const lines=[];for(const para of String(text||'').replaceAll('\t','    ').split(/\r?\n/)){let part='',used=0;for(const ch of para){const next=charWidth(ch,size);if(part&&used+next>maxWidth){lines.push(part);part=ch;used=next;}else{part+=ch;used+=next;}}lines.push(part);}return lines;}
  function addPage(){page=pdf.addPage([595,842]);page.drawRectangle({x:margin,y:817,width,height:7,color:navy});y=790;}
  function ensure(height){if(y-height<55)addPage();}
  function drawLine(text,{x=margin,size=10,color=navy,step=size*1.65}={}){ensure(step);page.drawText(String(text||''),{x,y,font,size,color});y-=step;}
  function paragraph(text,size=10,color=navy,maxWidth=width){for(const line of wrap(text,size,maxWidth))drawLine(line,{size,color});}
  function center(text,size,color=navy){const x=Math.max(margin,(595-font.widthOfTextAtSize(text,size))/2);page.drawText(text,{x,y,font,size,color});}
  function section(number,title,lines){ensure(34);page.drawText('제'+number+'조',{x:margin,y,font,size:10,color:navy});page.drawText(title,{x:margin+38,y,font,size:10,color:navy});y-=17;for(const line of lines)paragraph(line,9.2,navy,width-38);y-=5;}
  function tableRow(label,value){if(!value)return;const size=9.1,labelWidth=105,valueWidth=width-labelWidth,padding=8,lines=wrap(value,size,valueWidth-padding*2),height=Math.max(30,lines.length*13+padding*2);ensure(height);page.drawRectangle({x:margin,y:y-height,width:labelWidth,height,color:soft,borderColor:border,borderWidth:.8});page.drawRectangle({x:margin+labelWidth,y:y-height,width:valueWidth,height,borderColor:border,borderWidth:.8});page.drawText(label,{x:margin+padding,y:y-19,font,size:9.2,color:navy});let lineY=y-padding-9;for(const line of lines){page.drawText(line,{x:margin+labelWidth+padding,y:lineY,font,size,color:navy});lineY-=13;}y-=height;}
  addPage();center(c.title||'근로계약서',21);y-=31;const kind={standard:'표준 근로계약서',parttime:'단시간 근로계약서',other:'기타 계약서'}[c.contract_fields?.kind]||'근로계약서';center(kind,9.5,gray);y-=23;
  const written=c.contract_fields?.written_date||new Date(c.signed_at).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});page.drawText('작성일 '+written,{x:margin,y,font,size:8.5,color:gray});const number='계약서 번호 '+String(c.id).slice(0,8).toUpperCase();page.drawText(number,{x:contentRight-font.widthOfTextAtSize(number,8.5),y,font,size:8.5,color:gray});y-=13;page.drawLine({start:{x:margin,y},end:{x:contentRight,y},thickness:1.4,color:navy});y-=22;
  const parsed=parse(c.content,c.title),by=n=>parsed.groups.find(group=>group.number===String(n)),body=n=>by(n)?.lines.join(' · ')||'',partyInfo={};for(const line of by(7)?.lines||[]){const split=line.indexOf(':');if(split>0)partyInfo[line.slice(0,split).trim()]=line.slice(split+1).trim();}if(parsed.lead.length){paragraph(parsed.lead.join(' '),10);y-=10;}
  if(parsed.groups.length){const work=by(2);tableRow('계약기간',body(1));tableRow('근무장소',work?.lines.find(line=>line.startsWith('근무장소:'))?.replace(/^근무장소:\s*/,''));tableRow('업무 내용',work?.lines.find(line=>line.startsWith('업무 내용:'))?.replace(/^업무 내용:\s*/,''));tableRow('근무시간',body(3));tableRow('임금',body(5));y-=14;for(const group of parsed.groups.filter(group=>!['1','2','3','5','7'].includes(group.number)))section(group.number,group.title,group.lines);
  }else paragraph(c.content,10);
  ensure(215);y-=7;page.drawLine({start:{x:margin,y},end:{x:contentRight,y},thickness:.8,color:border});y-=16;center('양 당사자는 계약 내용을 충분히 확인하였으며 전자서명으로 계약을 체결합니다.',8.2,gray);y-=16;center(written,8.7,navy);y-=17;const boxWidth=(width-12)/2,boxHeight=135,top=y,boxes=[['사업주',[['사업장',partyInfo['사업장명']||c.property_name],['성명',partyInfo['사업주명']||c.employer_name],['연락처',partyInfo['사업장 연락처']],['주소',partyInfo['사업장 주소']]],c.employer_signature,c.sent_at],['근로자',[['성명',partyInfo['근로자명']||c.employee_name],['연락처',partyInfo['근로자 연락처']],['주소',partyInfo['근로자 주소']]],c.employee_signature,c.signed_at]];
  for(let index=0;index<boxes.length;index++){const[role,rows,src,time]=boxes[index],x=margin+index*(boxWidth+12),bottom=top-boxHeight;page.drawRectangle({x,y:bottom,width:boxWidth,height:boxHeight,borderColor:border,borderWidth:.8});page.drawText(role,{x:x+10,y:top-17,font,size:9.5,color:navy});let rowY=top-35;for(const[label,value]of rows.filter(row=>row[1])){page.drawText(label,{x:x+10,y:rowY,font,size:7.2,color:gray});const lines=wrap(value,7.9,boxWidth-72).slice(0,2);for(let i=0;i<lines.length;i++)page.drawText(lines[i],{x:x+57,y:rowY-i*9,font,size:7.9,color:navy});rowY-=Math.max(12,lines.length*9+2);}page.drawText('전자서명',{x:x+10,y:bottom+28,font,size:7.2,color:gray});if(src){const image=await pdf.embedPng(src),ratio=Math.min(105/image.width,30/image.height),w=image.width*ratio,h=image.height*ratio;page.drawImage(image,{x:x+boxWidth-w-10,y:bottom+15,width:w,height:h});}if(time){const stamp=new Date(time).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});page.drawText(stamp,{x:x+10,y:bottom+7,font,size:6.8,color:gray});}}
  y=top-boxHeight-15;paragraph('원문 확인값: '+c.content_hash,7.2,gray);pdf.getPages().forEach((p,i)=>{const label=`${i+1} / ${pdf.getPageCount()}`;p.drawText(label,{x:(595-font.widthOfTextAtSize(label,8))/2,y:30,font,size:8,color:gray});});return pdf.save();
 }
 return{validate,render};
}
