(async()=>{
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]),content=$('contractContent'),status=$('contractStatus'),params=new URLSearchParams(location.search);let session,employeeId=params.get('employee'),cache,dirty=false,working=false;
const call=(action,data={})=>OMSContracts.call(session.accessToken,action,data),stateName=s=>OMSContracts.status[s]||s;
const base=`{{지점}}의 사업주와 {{근무자}}는 아래의 근로조건을 확인합니다.

1. 계약기간
근로개시일: 【입력】
계약 종료일 또는 기간의 정함 없음: 【입력】

2. 근무장소 및 업무
근무장소: {{지점}} / 상세 주소: 【입력】
업무: {{직무}}

3. 근무시간 및 휴게
근무시간: {{출근}} ~ {{퇴근}}
휴게시간: 【입력】
근무요일 및 주별 근무시간: 【입력】

4. 휴일 및 휴가
주휴일: 【입력】
연차유급휴가: 적용되는 근로기준법에 따라 부여합니다.

5. 임금
기본급: {{급여}}
임금 산정기간: 【입력】
임금 지급일: {{급여일}}
지급방법: 근로자 본인 명의 계좌로 지급합니다.
주휴수당의 구성 및 계산방법: 【입력】
연장·야간·휴일근로의 조건 및 수당 계산방법: 【입력】
상여금·기타수당 및 공제항목: 【입력】

6. 사회보험
가입대상 및 적용 항목: 【입력】

7. 당사자 정보
사업체명·사업장 주소·연락처: 【입력】
근로자 성명: {{근무자}}
근로자 주소: 【입력】
근로자 연락처: {{연락처}}

8. 계약서 교부 및 기타 약정
서명 완료된 계약서는 양 당사자의 문서보관함에 PDF로 보관하며 열람·다운로드할 수 있습니다.
기타 특약: 【입력】
본 계약에서 정하지 않은 사항은 적용 법령 및 취업규칙에 따릅니다.`;
const builtin=[{id:'builtin-hourly',name:'시급제 기본 양식',content:base},{id:'builtin-monthly',name:'월급제 기본 양식',content:base.replace('임금 산정기간: 【입력】','임금 산정기간: 매월 1일부터 말일까지').replace('주휴수당의 구성 및 계산방법: 【입력】','월급 구성항목 및 주휴수당 포함 내역: 【입력】')}];
function fillTemplate(text){const d=cache?.defaults||{},amount=d.pay_type==='monthly'?d.monthly_salary:d.hourly_rate,values={'근무자':d.name,'지점':d.property,'직무':d.job,'출근':d.clock_in?.slice(0,5),'퇴근':d.clock_out?.slice(0,5),'연락처':d.contact,'급여':amount==null?'【입력】':(d.pay_type==='monthly'?'월급 ':'시급 ')+Number(amount).toLocaleString('ko-KR')+'원','급여일':d.pay_day?(d.pay_day===31?'매월 말일':'매월 '+d.pay_day+'일'):'【입력】'};return text.replace(/\{\{([^}]+)\}\}/g,(all,key)=>values[key]||'【입력】');}
async function run(fn){if(working)return;working=true;status.textContent='처리 중…';document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status.textContent=e.message;}finally{working=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function notify(result){if(!result.message_id||result.duplicate)return;try{await omgNotifications.send(session.accessToken,result.message_id);}catch{status.textContent+='\n메시지는 저장됐지만 휴대폰 알림 전달을 확인하지 못했습니다.';}}
function setLocation(id){const url=new URL(location.href);if(id)url.searchParams.set('id',id);else url.searchParams.delete('id');url.searchParams.delete('new');if(employeeId)url.searchParams.set('employee',employeeId);history.replaceState(null,'',url);}
async function list(){cache=await call('list',employeeId?{employee_id:employeeId}:{});dirty=false;setLocation(null);$('heading').textContent=cache.can_manage?(cache.defaults.name+' · 관련문서'):'내 문서';content.innerHTML=(cache.can_manage?'<div class="contract-actions"><button id="newContract" class="primary">계약서 작성</button><button id="templates">양식 관리</button></div>':'')+'<section class="contract-box"><h2>근로계약서</h2><div id="contractList"></div></section>';const host=$('contractList');host.innerHTML=cache.contracts.map(c=>`<button type="button" class="contract-row" data-id="${c.id}"><span><strong>${esc(c.title)}</strong><small>${new Date(c.created_at).toLocaleDateString('ko-KR')}${c.viewed_at?' · 열람함':''}</small></span><span class="contract-state">${stateName(c.status==='draft'&&c.contract_ready?'ready':c.status)} ›</span></button>`).join('')||'<p class="contract-note">근로계약서 · 작성전</p>';host.querySelectorAll('button').forEach(b=>b.onclick=()=>run(()=>open(b.dataset.id)));if(cache.can_manage){$('newContract').onclick=()=>edit();$('templates').onclick=()=>templates();}}
async function open(id){const result=await call('get',{id}),c=result.contract;employeeId=c.employee_id;setLocation(id);$('heading').textContent='근로계약서';if(result.can_manage&&c.status==='draft'){if(!cache)cache=await call('list',{employee_id:employeeId});edit(c);return;}view(c,result.can_manage);status.textContent='';}
function templates(){const d=document.createElement('dialog');d.innerHTML='<h2>계약서 양식 관리</h2><label>불러올 양식<select id="templateChoice"></select></label><label>양식 이름<input id="templateName" maxlength="80"></label><label>내용<textarea id="templateText" maxlength="30000"></textarea></label><p class="contract-note">{{근무자}}, {{지점}}, {{직무}}, {{출근}}, {{퇴근}}, {{급여}}, {{급여일}}, {{연락처}}는 계약서 작성 시 자동으로 채워집니다.</p><p class="template-status" role="status"></p><div class="contract-actions"><button class="primary" id="templateSave">새 양식으로 저장</button><button id="templateUpdate">선택 양식 덮어쓰기</button><button id="templateClose">닫기</button></div>';document.querySelector('main').append(d);const options=[...builtin,...cache.templates];d.querySelector('select').innerHTML=options.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');let chosen=options[0];function choose(){chosen=options.find(t=>t.id===d.querySelector('select').value);d.querySelector('#templateName').value=chosen.name;d.querySelector('#templateText').value=chosen.content;d.querySelector('#templateUpdate').hidden=chosen.id.startsWith('builtin');}d.querySelector('select').onchange=choose;choose();window.omgSelectPicker?.mount(d.querySelector('select'),{title:'계약서 양식 선택'});async function save(overwrite){const msg=d.querySelector('.template-status');d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await call('template_save',{employee_id:employeeId,id:overwrite?chosen.id:crypto.randomUUID(),name:d.querySelector('#templateName').value,content:d.querySelector('#templateText').value});cache=await call('list',{employee_id:employeeId});const editorChoice=$('chooseTemplate');if(editorChoice){const value=editorChoice.value;editorChoice.innerHTML='<option value="">양식을 선택하세요</option>'+[...builtin,...cache.templates].map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');editorChoice.value=value;}options.splice(0,options.length,...builtin,...cache.templates);d.querySelector('select').innerHTML=options.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');d.querySelector('select').value=chosen.id;msg.textContent='양식을 저장했습니다.';}catch(e){msg.textContent=e.message;}finally{d.querySelectorAll('button').forEach(b=>b.disabled=false);}}d.querySelector('#templateSave').onclick=()=>save(false);d.querySelector('#templateUpdate').onclick=()=>save(true);d.querySelector('#templateClose').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();}
function edit(existing){const c=existing?{...existing}:{id:crypto.randomUUID(),version:0,title:'근로계약서',content:fillTemplate(builtin[cache.defaults.pay_type==='monthly'?1:0].content),employer_name:cache.defaults.business_info?.employer_name||''};const options=[...builtin,...cache.templates];content.innerHTML='<div class="contract-actions"><button id="toList">‹ 문서함</button><button id="manageTemplates">양식 관리</button></div><section class="contract-box"><label>양식 선택<select id="chooseTemplate"></select></label><label>계약서 제목<input id="contractTitle" maxlength="120"></label><label>사업주 성명 / 대표자<input id="employerName" maxlength="100"></label><label>계약 내용<textarea id="contractBody" maxlength="30000"></textarea></label><p class="contract-note">근로조건을 작성하고 전문을 확인한 뒤 전송하세요. 기본 양식은 <a href="https://www.moel.go.kr/mainpop2.do" target="_blank" rel="noopener">고용노동부 작성 항목</a>을 참고한 편집용 초안입니다.</p><div class="contract-actions"><button id="preview">미리보기</button><button id="saveDraft">임시저장</button></div></section><section class="contract-box"><h2>사업주 서명</h2><div id="ownerPad"></div><label class="contract-confirm"><input type="checkbox" id="ownerConfirm">최종 내용을 확인했으며, 전자서명하고 근무자에게 발송합니다.</label><button id="sendContract" class="primary">서명 요청 보내기</button></section>';const select=$('chooseTemplate');select.innerHTML='<option value="">양식을 선택하세요</option>'+options.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('contractTitle').value=c.title;$('contractBody').value=c.content;$('employerName').value=c.employer_name;const pad=OMSContracts.signature($('ownerPad'));function changed(){dirty=true;$('ownerConfirm').checked=false;pad.clear();}for(const id of ['contractTitle','contractBody','employerName'])$(id).oninput=changed;select.onchange=()=>{const t=[...builtin,...cache.templates].find(t=>t.id===select.value);if(!t)return;if(dirty&&!confirm('작성 중인 내용을 선택한 양식으로 바꿀까요?'))return;$('contractBody').value=fillTemplate(t.content);structured.manual();changed();};$('manageTemplates').onclick=templates;$('toList').onclick=()=>{if(!dirty||confirm('저장하지 않은 내용을 닫을까요?'))run(list);};
window.omgSelectPicker?.mount(select,{title:'저장된 양식 불러오기',placeholder:'양식을 선택하세요'});const structured=window.OMSContractForm.mount({body:$('contractBody'),employer:$('employerName'),title:$('contractTitle'),defaults:cache.defaults,existing:c.version||c.contract_fields?c:null,changed});const complete=document.createElement('button');complete.id='completeContract';complete.textContent='작성 완료';complete.className='primary';$('saveDraft').after(complete);complete.onclick=()=>run(async()=>{structured.validate();await save(true);status.textContent='작성이 완료되었습니다. 내용을 확인하고 사업주 서명 후 전송해주세요.';});
function values(){return{contract_fields:structured.fields(),id:c.id,version:c.version,employee_id:employeeId,title:$('contractTitle').value.trim(),content:$('contractBody').value,employer_name:$('employerName').value.trim()};}
async function save(ready=false){const v={...values(),contract_ready:ready};if(!v.title||!v.content.trim())throw Error('계약서 제목과 내용을 입력해주세요.');const r=await call('draft',v);Object.assign(c,r.contract);dirty=false;setLocation(c.id);return r;}
$('saveDraft').onclick=()=>run(async()=>{await save();status.textContent='임시저장했습니다.';});$('preview').onclick=()=>{const d=document.createElement('dialog');d.className='contract-preview-dialog';d.innerHTML='<div class="contract-paper"></div><div class="contract-actions"><button>닫기</button></div>';OMSContractPaper.render(d.querySelector('.contract-paper'),{title:$('contractTitle').value,content:$('contractBody').value,employer_name:$('employerName').value},{signatures:false});document.querySelector('main').append(d);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();};$('sendContract').onclick=()=>run(async()=>{structured.validate();if(!$('ownerConfirm').checked)throw Error('계약 내용을 확인하고 동의해주세요.');const signature=pad.get();if(!confirm('이 계약서를 근무자에게 보내 서명을 요청할까요? 발송한 내용은 변경할 수 없습니다.')){status.textContent='';return;}await save(true);const result=await call('send',{id:c.id,version:c.version,signature,confirmed:true});view(result.contract,true);status.textContent='근태관리 알림으로 서명을 요청했습니다.';await notify(result);});status.textContent='';}
function view(c,manager){dirty=false;content.innerHTML='<div class="contract-actions"><button id="toList">‹ 문서함</button></div><div class="contract-state">'+stateName(c.status==='draft'&&c.contract_ready?'ready':c.status)+'</div><section class="contract-box contract-document"><div class="contract-paper"></div></section>'+(c.change_reason?'<section class="contract-box"><h2>수정 요청</h2><p>'+esc(c.change_reason)+'</p></section>':'')+'<section class="contract-box" id="contractControls"></section>';OMSContractPaper.render(content.querySelector('.contract-paper'),c,{signatures:c.status==='signed'});$('toList').onclick=()=>run(list);const control=$('contractControls');if(c.status!=='signed'&&c.employer_signature){const owner=document.createElement('section');owner.className='contract-box';owner.innerHTML='<h2>사업주 확인</h2><p>'+esc(c.employer_name)+'</p><img class="contract-owner-signature" alt="사업주 서명">';owner.querySelector('img').src=c.employer_signature;control.before(owner);}if(c.status==='signed'){control.innerHTML='<h2>서명 완료</h2><p class="contract-note">'+esc(new Date(c.signed_at).toLocaleString('ko-KR'))+'</p><button id="contractPdf" class="primary">완료 계약서 PDF 다운로드</button>';$('contractPdf').onclick=()=>run(async()=>{const result=await call('pdf',{id:c.id});status.textContent='';location.href=result.url;});}else if(!manager&&c.status==='sent'){control.innerHTML='<h2>근로자 서명</h2><div id="workerPad"></div><label class="contract-confirm"><input type="checkbox" id="workerConfirm">계약 내용 전체를 확인했고, 본인이 전자서명하며 완료된 PDF를 내 문서함으로 교부받는 데 동의합니다.</label><div class="contract-actions"><button id="requestChange">수정 요청</button><button id="signContract" class="primary">서명 완료</button></div>';const pad=OMSContracts.signature($('workerPad'));$('requestChange').onclick=()=>{const reason=prompt('수정이 필요한 내용을 적어주세요.');if(reason?.trim())run(async()=>{const r=await call('request_change',{id:c.id,reason});view(r.contract,false);status.textContent='수정 요청을 보냈습니다.';await notify(r);});};$('signContract').onclick=()=>run(async()=>{if(!$('workerConfirm').checked)throw Error('내용 확인 및 전자서명에 동의해주세요.');const signature=pad.get();const r=await call('sign',{id:c.id,version:c.version,content_hash:c.content_hash,signature,confirmed:true});view(r.contract,false);status.textContent=r.pdf_message||'서명이 완료되고 PDF가 문서함에 보관되었습니다.';await notify(r);});}else{control.innerHTML='<p class="contract-note">'+(c.status==='sent'?'근무자의 확인과 서명을 기다리고 있습니다.':'이 계약서는 서명할 수 없습니다.')+'</p>';}
if(manager&&c.status!=='signed'){const actions=document.createElement('div');actions.className='contract-actions';actions.innerHTML='<button id="copyContract">새 계약서로 복사</button>'+(c.status!=='cancelled'?'<button id="cancelContract" class="danger">요청 취소</button>':'');control.append(actions);$('copyContract').onclick=()=>run(async()=>{cache=await call('list',{employee_id:c.employee_id});edit({...c,id:crypto.randomUUID(),version:0,status:'draft'});});if($('cancelContract'))$('cancelContract').onclick=()=>{if(confirm('이 계약서의 서명 요청을 취소할까요?'))run(async()=>{const r=await call('cancel',{id:c.id});view(r.contract,true);status.textContent='취소했습니다.';});};}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
try{session=await omgSession.require({allowCompleted:true});if(!session)return;if(session.sessionKind!=='owner'){$('back').href='employee-profile.html';$('back').textContent='‹ 내 정보';}if(session.sessionKind==='staff'&&params.get('from')==='notification'){location.replace('employee-profile.html?contract='+encodeURIComponent(params.get('id')));return;}if(params.get('id'))await open(params.get('id'));else{await list();if(params.get('new')&&cache.can_manage)edit();}status.textContent='';}catch(e){status.textContent=e.message;}
})();
