window.OMSDocumentVault=(()=>{
 const MB=1024*1024,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
 const icons=['<path d="M14 3H5v18h14V8M14 3v5h5M8 13h8M8 17h5"/>','<path d="m3 11 18-8-8 18-2-8-8-2Zm8 2L21 3"/>','<path d="m4 16 12-12 4 4L8 20H4v-4ZM3 22h18"/>','<path d="m5 12 4 4L19 6"/>'];
 const icon=i=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[i]+'</svg>';
 function popup(message,confirm=false,kind='new'){return new Promise(resolve=>{const d=document.createElement('dialog');d.className='oms-document-popup';d.innerHTML='<h3>'+ (confirm?(kind==='delete'?'문서 삭제':'신규 계약서 작성'):'문서보관함 안내')+'</h3><p></p><div>'+(confirm?'<button data-no type="button">취소</button>':'')+'<button data-yes type="button">'+(confirm?(kind==='delete'?'삭제':'신규작성'):'확인')+'</button></div>';d.querySelector('p').textContent=message;document.body.append(d);let result=false;d.querySelector('[data-yes]').onclick=()=>{result=true;d.close();};if(confirm)d.querySelector('[data-no]').onclick=()=>d.close();d.onclose=()=>{d.remove();resolve(result);};d.showModal();});}
 function open({employeeId,name,token,documents}){
  const d=document.createElement('dialog');d.className='employee-document-dialog oms-vault';d.innerHTML='<header><div><small></small><h2>관련문서</h2></div><button class="doc-close" type="button" aria-label="닫기">×</button></header><section class="vault-panel"><div class="vault-title"><h3>근로계약서 관리</h3><span class="vault-badge"></span></div><ol class="vault-flow"></ol><div class="vault-current"><strong></strong><p></p></div><div class="vault-actions"></div><a class="vault-history">계약서 전체 내역·양식 관리 ›</a></section><section class="vault-panel"><div class="vault-title"><div class="vault-heading"><h3>문서보관함</h3><button class="vault-help" type="button" aria-label="문서보관함 안내">?</button></div><label class="vault-upload">＋ 문서 추가<input type="file" accept=".pdf,application/pdf" hidden></label></div><div class="vault-files"></div></section><p class="doc-status" role="status"></p>';
  d.querySelector('header small').textContent=name;d.querySelector('.vault-history').href='contracts.html?employee='+encodeURIComponent(employeeId);document.body.append(d);d.showModal();d.querySelector('.doc-close').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('.vault-help').onclick=()=>popup('완료된 계약서를 보관합니다.\nPDF 문서만 추가할 수 있습니다.\n파일당 10MB 이하, 근무자별 문서함 총 50MB까지 보관할 수 있습니다.');const status=d.querySelector('.doc-status'),files=d.querySelector('.vault-files'),picker=d.querySelector('input');let used=0,contracts=[],loaded=false;
  const newUrl='contracts.html?employee='+encodeURIComponent(employeeId)+'&new=1';
  function renderLoading(){d.classList.add('vault-loading');d.querySelector('.vault-badge').textContent='확인 중';d.querySelector('.vault-flow').innerHTML=['계약서 작성','전송','근로자 서명','완료'].map((label,i)=>'<li><span>'+icon(i)+'</span><small>'+label+'</small></li>').join('');d.querySelector('.vault-current strong').textContent='계약 정보를 불러오고 있습니다';d.querySelector('.vault-current p').innerHTML='<span class="vault-loading-dots" aria-label="불러오는 중"><i></i><i></i><i></i></span>';d.querySelector('.vault-actions').innerHTML='<span class="vault-action-skeleton" aria-hidden="true"></span><span class="vault-action-skeleton" aria-hidden="true"></span>';files.innerHTML='<div class="vault-file-skeleton" aria-hidden="true"><i></i><span></span></div><div class="vault-file-skeleton" aria-hidden="true"><i></i><span></span></div>';status.textContent='';}
  async function pdf(c){try{const r=await OMSContracts.call(token,'pdf',{id:c.id});location.href=r.url;}catch(e){await popup(e.message);}}
  function renderContract(){d.classList.remove('vault-loading');const current=contracts.find(c=>!['cancelled','signed'].includes(c.status))||contracts.find(c=>c.status==='signed');const pendingPdf=current?.status==='signed'&&!current.pdf_ready,complete=current?.status==='signed'&&current.pdf_ready,stage=complete||pendingPdf?3:current?.status==='sent'?2:current?.contract_ready?1:0;
   d.querySelector('.vault-badge').textContent=complete?'완료':pendingPdf?'PDF 보관 대기':current?.status==='revision_requested'?'수정 요청':current?.status==='sent'?'전송완료':current?.contract_ready?'작성완료':current?'작성 중':'작성전';
   d.querySelector('.vault-flow').innerHTML=['계약서 작성','전송','근로자 서명','완료'].map((label,i)=>'<li class="'+(i<stage||complete?'done':i===stage?'active':'')+'"><span>'+icon(i)+'</span><small>'+label+'</small></li>').join('');
   d.querySelector('.vault-current strong').textContent=complete?'근로계약서 📄':pendingPdf?'PDF 보관을 완료해주세요':stage===2?'근로자 서명을 기다리고 있어요':stage===1?'작성한 계약서를 전송하세요':'계약서를 작성해주세요';d.querySelector('.vault-current p').textContent=complete?'서명 완료된 PDF가 아래 문서보관함에 보관되어 있습니다.':pendingPdf?'서명은 완료되었습니다. 문서함 용량을 확인하고 PDF 보관을 다시 시도해주세요.':stage===2?'근무자가 내용을 확인하고 서명하면 PDF로 보관됩니다.':'근로조건을 확인하고 사업주 서명 후 전송해주세요.';
   const actions=d.querySelector('.vault-actions');actions.replaceChildren();if(complete){const create=document.createElement('button');create.type='button';create.textContent='신규작성';create.onclick=async()=>{if(await popup('계약서를 새로 작성하시겠습니까? 기존 완료된 PDF는 삭제되지 않습니다.',true))location.href=newUrl;};const view=document.createElement('button');view.type='button';view.className='vault-primary';view.textContent='보관된 PDF 보기';view.onclick=()=>pdf(current);actions.append(create,view);}else if(pendingPdf){const retry=document.createElement('button');retry.type='button';retry.className='vault-primary';retry.textContent='PDF 보관 다시 시도';retry.onclick=()=>pdf(current);actions.append(retry);}else{const a=document.createElement('a');a.className='vault-primary';a.textContent=stage===2?'전송한 계약서 보기':current?'계약서 이어서 작성':'계약서 작성';a.href=current?'contracts.html?id='+current.id:newUrl;actions.append(a);}
  }
  async function refresh(){loaded=false;picker.disabled=true;status.textContent='';try{const [data,c]=await Promise.all([documents(token,employeeId,'list'),OMSContracts.call(token,'list',{employee_id:employeeId})]);used=Number(data.used_bytes||0);contracts=c.contracts;renderContract();files.replaceChildren();
   for(const contract of contracts.filter(c=>c.status==='signed')){const row=document.createElement('button');row.type='button';row.className='vault-file contract-pdf';row.innerHTML='<span><strong>근로계약서 📄</strong><small>'+esc(new Date(contract.signed_at).toLocaleDateString('ko-KR'))+' · 서명 완료본</small></span><b>PDF ›</b>';row.onclick=()=>pdf(contract);files.append(row);}
   for(const doc of data.documents){const row=document.createElement('div');row.className='vault-file';row.innerHTML='<span><strong>'+esc(doc.filename)+'</strong><small>'+esc(new Date(doc.created_at).toLocaleDateString('ko-KR'))+' · '+(doc.size/MB).toFixed(2)+'MB</small></span><button type="button" data-open>열기</button><button type="button" data-delete>삭제</button>';row.querySelector('[data-open]').onclick=async()=>{try{const r=await documents(token,employeeId,'open',{document_id:doc.id});location.href=r.url;}catch(e){popup(e.message);}};row.querySelector('[data-delete]').onclick=async()=>{if(!await popup('이 첨부 문서를 삭제하시겠습니까?',true,'delete'))return;try{await documents(token,employeeId,'delete',{document_id:doc.id});await refresh();}catch(e){popup(e.message);}};files.append(row);}
   loaded=true;status.textContent='';}catch(e){d.classList.remove('vault-loading');d.querySelector('.vault-badge').textContent='연결 확인';d.querySelector('.vault-current strong').textContent='문서 정보를 불러오지 못했습니다';d.querySelector('.vault-current p').textContent=e.message;const retry=document.createElement('button');retry.type='button';retry.className='vault-primary';retry.textContent='다시 불러오기';retry.onclick=()=>{renderLoading();refresh();};d.querySelector('.vault-actions').replaceChildren(retry);files.replaceChildren();status.textContent='';}finally{picker.disabled=!loaded;}}
  picker.onchange=async()=>{const file=picker.files[0];if(!file)return;picker.disabled=true;try{if(!loaded)throw Error('문서함을 불러온 후 다시 시도해주세요.');if(file.size>10*MB)throw Error('파일 한 개는 10MB 이하만 업로드할 수 있습니다. 파일 용량을 줄여 다시 선택해주세요.');if(!/\.pdf$/i.test(file.name)||new TextDecoder().decode(await file.slice(0,5).arrayBuffer())!=='%PDF-')throw Error('PDF 문서만 추가할 수 있습니다. 문서를 PDF로 저장한 후 선택해주세요.');if(used+file.size>50*MB)throw Error('문서보관함은 근무자별 총 50MB까지 사용할 수 있습니다. 불필요한 첨부 문서를 삭제한 후 다시 시도해주세요.');status.textContent='업로드 중…';await documents(token,employeeId,'upload',{file});await refresh();}catch(e){await popup(e.message);status.textContent='';}finally{picker.disabled=!loaded;picker.value='';}};renderLoading();refresh();
 }
 return{open,popup};
})();
