window.MessageHub=(()=>{
 let tab='guest',state,callbacks,rows=[],actor='',cursor=null,busy=false,timer,property='',paged=false,filter='all',query='',canManage=false;
 const $=id=>document.getElementById(id),alertItem=i=>['announcement','attendance_warning','attendance_approval','property_share_approval'].includes(i.message_type)||i.sender_type==='system';
 function setTab(value){tab=['guest','staff','alerts'].includes(value)?value:'guest';document.querySelectorAll('[data-hub]').forEach(b=>{b.classList.toggle('active',b.dataset.hub===tab);b.setAttribute('aria-selected',String(b.dataset.hub===tab));});$('guestPane').hidden=tab!=='guest';$('list').hidden=tab!=='alerts';document.querySelector('.mail-tabs').hidden=tab!=='alerts'||!canManage;StaffConversations.show(tab==='staff');$('composeToggle').hidden=tab==='guest'||(tab==='alerts'&&!canManage);$('searchToggle').hidden=false;$('messageSearch').hidden=true;$('searchToggle').setAttribute('aria-expanded','false');$('messageSearchInput').value='';query='';StaffConversations.setQuery('');callbacks?.clearSearch();const u=new URL(location.href);u.searchParams.set('tab',tab);history.replaceState(history.state,'',u);callbacks?.render();if(tab==='guest')load();}
 function render(){const G=GuestSupport;let visible=rows.filter(r=>(filter!=='waiting'||(!r.assigned_key&&r.status==='open'))&&(filter!=='mine'||r.assigned_key===actor)&&(filter!=='closed'||r.status==='closed')&&(!query||`${r.guest_name} ${r.room_number||''} ${r.preview||''}`.toLowerCase().includes(query)));
 $('guestRooms').innerHTML=visible.map(r=>`<a class="hub-room ${Number(r.unread)?'is-unread':''}" href="guest-chat.html?room=${encodeURIComponent(r.id)}"><div class="hub-room-top"><strong>${G.esc(r.guest_name)} · ${G.esc(r.room_number||'객실 미정')}</strong><time>${G.esc(new Date(r.updated_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</time></div><p>${G.esc(r.preview||'현장 게스트와의 대화가 시작되었습니다.')}</p><div class="hub-room-foot"><span>${G.esc(r.property_name)} · ${G.esc(r.status==='closed'?'응답 완료':r.assigned_name?r.assigned_name+' 대응 중':'미응답 · 담당 대기')}</span>${Number(r.unread)?`<b class="hub-count">${Number(r.unread)}</b>`:''}</div></a>`).join('')||'<div class="empty">표시할 대화가 없습니다.</div>';
 $('waitingCount').textContent=rows.filter(r=>!r.assigned_key&&r.status==='open').length;$('mineCount').textContent=rows.filter(r=>r.assigned_key===actor).length;
 $('guestCount').textContent=rows.reduce((n,r)=>n+Number(r.unread||0),0)||'';
 }
 async function load(older=false){if(!state||busy||document.hidden||tab!=='guest')return;busy=true;clearTimeout(timer);try{const v=await GuestSupport.call('rooms',{property_id:property,...(older&&cursor?{before_updated:cursor.updated_at,before_id:cursor.id}:{})},{access_token:state.accessToken});actor=v.actor.key;const map=new Map(rows.map(r=>[r.id,r]));v.rooms.forEach(r=>map.set(r.id,r));rows=[...map.values()].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)||b.id.localeCompare(a.id));if(older)paged=true;if(older||!paged){cursor=v.rooms.at(-1);$('guestOlder').hidden=v.rooms.length<50;}if(!$('hubProperty').dataset.loaded){$('hubProperty').replaceChildren(new Option('전체 지점',''),...v.properties.map(p=>new Option(p.id===state.propertyId?'본지점 · '+p.name:p.name,p.id)));$('hubProperty').value=property;$('hubProperty').dataset.loaded='1';}$('guestError').textContent='';render();}catch(e){$('guestError').textContent=e.message;}finally{busy=false;timer=setTimeout(load,5000);}}
 return {search(value){query=value.trim().toLowerCase();if(tab==='guest')render();if(tab==='staff')StaffConversations.setQuery(value);},isStaff:()=>tab==='staff',matches:i=>tab==='alerts'?alertItem(i):!alertItem(i),selectFor:i=>setTab(alertItem(i)?'alerts':'staff'),updateCounts(data){canManage=!!data.can_manage;document.querySelector('.mail-tabs').hidden=tab!=='alerts'||!canManage;$('composeToggle').hidden=tab==='guest'||(tab==='alerts'&&!canManage);StaffConversations.update(data);if(!$('staffCount'))return;const items=(data.messages||[]).filter(i=>!i.is_sender&&!i.read_at);$('alertsCount').textContent=items.filter(alertItem).length||'';},async init(s,c){state=s;callbacks=c;property=s.propertyId||'';
 const nav=document.createElement('nav');nav.className='hub-tabs';nav.setAttribute('aria-label','메세지 종류');nav.innerHTML='<button data-hub="guest" type="button">게스트 <small id="guestCount"></small></button><button data-hub="staff" type="button">직원 <small id="staffCount"></small></button><button data-hub="alerts" type="button">알림 <small id="alertsCount"></small></button>';document.querySelector('.head').after(nav);StaffConversations.init(s,nav);nav.append($('searchToggle'));const actions=document.createElement('div');actions.className='message-top-actions';document.querySelector('.top').append(actions);actions.append($('composeToggle'),$('refresh'));nav.after($('messageSearch'));$('messageSearchInput').placeholder='이름 또는 대화 검색';
 const pane=document.createElement('section');pane.id='guestPane';pane.innerHTML='<div class="hub-toolbar"><select id="hubProperty" aria-label="지점 선택"><option>본지점</option></select></div><div class="hub-filters"><button data-filter="all" class="active">전체</button><button data-filter="waiting">미응답 <span id="waitingCount">0</span></button><button data-filter="mine">내 담당 <span id="mineCount">0</span></button><button data-filter="closed">완료</button></div><div id="guestError" role="status"></div><div id="guestRooms"></div><button id="guestOlder" type="button" hidden>이전 대화 더 보기</button>';$('messageSearch').after(pane);
 nav.querySelectorAll('[data-hub]').forEach(b=>b.onclick=()=>setTab(b.dataset.hub));pane.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;pane.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});$('hubProperty').onchange=e=>{property=e.target.value;rows=[];cursor=null;paged=false;load();};$('guestOlder').onclick=()=>load(true);$('refresh').onclick=()=>{c.load();load();StaffConversations.load();};document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden)load();});window.addEventListener('pagehide',()=>clearTimeout(timer));const p=new URLSearchParams(location.search);setTab(p.has('compose')||p.has('recipient_employee_id')||p.has('message_id')?'staff':p.get('tab')||'guest');}};
})();
