window.MessageHub=(()=>{
 let tab='guest',state,callbacks,rows=[],cursor=null,busy=false,timer,propertyIds=null,properties=[],selectionVersion=0,paged=false,query='',canManage=false;
 const $=id=>document.getElementById(id),alertItem=i=>['announcement','attendance_warning','attendance_approval','property_share_approval'].includes(i.message_type)||i.sender_type==='system';
 function setTab(value){tab=['guest','staff','alerts','approvals'].includes(value)?value:'guest';document.querySelectorAll('[data-hub]').forEach(b=>{b.classList.toggle('active',b.dataset.hub===tab);b.setAttribute('aria-selected',String(b.dataset.hub===tab));});$('guestPane').hidden=tab!=='guest';$('hubProperty').hidden=tab!=='guest';$('list').hidden=!['alerts','approvals'].includes(tab);document.querySelector('.mail-tabs').hidden=true;callbacks?.mailbox(tab==='approvals'?'approvals':'inbox');$('approvalFilterHost').hidden=tab!=='approvals'||!canManage;StaffConversations.show(tab==='staff');$('composeToggle').hidden=tab==='guest'||tab==='approvals'||(tab==='alerts'&&!canManage);$('searchToggle').hidden=false;$('messageSearch').hidden=true;$('searchToggle').setAttribute('aria-expanded','false');$('messageSearchInput').value='';query='';StaffConversations.setQuery('');callbacks?.clearSearch();const u=new URL(location.href);u.searchParams.set('tab',tab);history.replaceState(history.state,'',u);callbacks?.render();if(tab==='guest')load();}
 function render(){const G=GuestSupport;let visible=rows.filter(r=>(!query||`${r.guest_name} ${r.room_number||''} ${r.preview||''}`.toLowerCase().includes(query)));
 $('guestRooms').innerHTML=visible.map(r=>`<a class="hub-room guest-room ${Number(r.unread)?'is-unread':''}" href="guest-chat.html?room=${encodeURIComponent(r.id)}"><span class="guest-avatar" aria-label="${G.esc(r.room_number?'객실 '+r.room_number:'객실 미정')}"><span class="guest-person"><svg viewBox="0 0 24 24" width="38" height="38" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="5"/><path d="M20 21a8 8 0 0 0-16 0"/></svg></span><span class="guest-room-number">${G.esc(r.room_number||'--')}</span></span><span class="hub-room-copy"><strong>${G.esc(r.guest_name)}</strong><span class="hub-room-preview">${G.esc(r.preview||'현장 게스트와의 대화가 시작되었습니다.')}</span></span><span class="hub-room-meta"><time>${G.esc(new Date(r.updated_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</time><span>${G.esc(r.property_name)}</span><span class="hub-room-status ${r.status==='closed'?'is-complete':''}"><span>${G.esc(r.status==='closed'?'응답 완료':r.assigned_name?r.assigned_name+' 대응 중':'미응답 · 담당 대기')}</span>${Number(r.unread)?`<b class="hub-count" aria-label="안 읽은 메시지 ${Number(r.unread)}개">${Number(r.unread)}</b>`:''}</span></span></a>`).join('')||'<div class="empty">표시할 대화가 없습니다.</div>';
 $('guestCount').textContent=rows.reduce((n,r)=>n+Number(r.unread||0),0)||'';
 }
 async function load(older=false){
  if(!state||busy||document.hidden||tab!=='guest')return;
  busy=true;clearTimeout(timer);const version=selectionVersion;
  try{
   const selected=propertyIds&&propertyIds.length<properties.length?propertyIds:[''];
   const pages=await Promise.all(selected.map(id=>GuestSupport.call('rooms',{property_id:id,...(older&&cursor?{before_updated:cursor.updated_at,before_id:cursor.id}:{})},{access_token:state.accessToken})));
   if(version!==selectionVersion)return;
   const batch=[...new Map(pages.flatMap(v=>v.rooms).map(r=>[r.id,r])).values()].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)||b.id.localeCompare(a.id)).slice(0,50);
   const map=new Map(rows.map(r=>[r.id,r]));batch.forEach(r=>map.set(r.id,r));rows=[...map.values()].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)||b.id.localeCompare(a.id));
   if(older)paged=true;if(older||!paged){cursor=batch.at(-1);$('guestOlder').hidden=batch.length<50;}
   if(!$('hubProperty').dataset.loaded){
    properties=pages[0].properties;
    omgPropertySelector.mountStatic({properties:properties.map(p=>({property_id:p.id,property_name:p.name,is_own:p.id===state.propertyId})),permission:'messages',alwaysShow:true,host:$('hubProperty'),defaultSelection:'all',onChange:ids=>{propertyIds=ids;selectionVersion++;rows=[];cursor=null;paged=false;render();load();}});
    $('hubProperty').dataset.loaded='1';
   }
   $('guestError').textContent='';render();
  }catch(e){if(version===selectionVersion)$('guestError').textContent=e.message;}
  finally{busy=false;timer=setTimeout(load,version===selectionVersion?5000:0);}
 }

 return {search(value){query=value.trim().toLowerCase();if(tab==='guest')render();if(tab==='staff')StaffConversations.setQuery(value);},isStaff:()=>tab==='staff',matches:i=>['alerts','approvals'].includes(tab)?alertItem(i):!alertItem(i),selectFor:i=>setTab(['attendance_approval','property_share_approval'].includes(i.message_type)&&canManage?'approvals':alertItem(i)?'alerts':'staff'),updateCounts(data){canManage=!!data.can_manage;document.querySelector('.mail-tabs').hidden=true;$('hubAlertsLabel').textContent=canManage?'공지':'알림';document.querySelector('[data-hub=approvals]').hidden=!canManage;document.querySelector('.hub-tabs').classList.toggle('owner-hub',canManage);$('approvalFilterHost').hidden=tab!=='approvals'||!canManage;$('composeToggle').hidden=tab==='guest'||tab==='approvals'||(tab==='alerts'&&!canManage);StaffConversations.update(data);if(!$('staffCount'))return;const items=(data.messages||[]).filter(i=>!i.is_sender&&!i.read_at);$('alertsCount').textContent=items.filter(alertItem).length||'';},async init(s,c){state=s;callbacks=c;propertyIds=null;
 const nav=document.createElement('nav');nav.className='hub-tabs';nav.setAttribute('aria-label','메세지 종류');nav.innerHTML='<button data-hub="guest" type="button">게스트 <small id="guestCount"></small></button><button data-hub="staff" type="button">직원 <small id="staffCount"></small></button><button data-hub="alerts" type="button"><span id="hubAlertsLabel">알림</span> <small id="alertsCount"></small></button><button data-hub="approvals" type="button" hidden>결재</button>';document.querySelector('.head').after(nav);StaffConversations.init(s,nav);const actions=document.createElement('div');actions.className='hub-actions';const propertyHost=document.createElement('div');propertyHost.id='hubProperty';propertyHost.setAttribute('aria-label','지점 선택');actions.append(propertyHost,$('composeToggle'),$('searchToggle'));nav.append(actions);const filterHost=document.createElement('div');filterHost.id='approvalFilterHost';filterHost.hidden=true;filterHost.append($('approvalFilter'));actions.insertBefore(filterHost,$('searchToggle'));nav.after($('messageSearch'));$('messageSearchInput').placeholder='이름 또는 대화 검색';
 $('searchToggle').innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>';
 $('composeToggle').innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M16 3a2.12 2.12 0 0 1 3 3l-9 9-4 1 1-4Z"/></svg>';
 const pane=document.createElement('section');pane.id='guestPane';pane.innerHTML='<div id="guestError" role="status"></div><div id="guestRooms"></div><button id="guestOlder" type="button" hidden>이전 대화 더 보기</button>';$('messageSearch').after(pane);
 nav.querySelectorAll('[data-hub]').forEach(b=>b.onclick=()=>setTab(b.dataset.hub));$('guestOlder').onclick=()=>load(true);$('refresh').onclick=()=>{c.load();load();StaffConversations.load();};document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden)load();});window.addEventListener('pagehide',()=>clearTimeout(timer));const p=new URLSearchParams(location.search);setTab(p.has('compose')||p.has('recipient_employee_id')||p.has('message_id')?'staff':p.get('tab')||'guest');}};
})();
