/* Alert delivery uses the original recipient records; reading a card never acknowledges it. */
window.NotificationBot=(()=>{
 const $=id=>document.getElementById(id),e=v=>GuestSupport.esc(String(v??''));
 let session,callbacks,data={messages:[]},properties=null,profiles=[],query='',roomProperty=null,announcementMode=false,profileLoaded=false,refreshing=false,alertBusy=false,alertsLoaded=false,alertMessages=[],unreadByProperty={},cursor=null,hasOlder=false;
 const isAlert=i=>!!StaffChat.contractId(i.message)||['announcement','attendance_warning','attendance_approval','property_share_approval','holiday_approval','holiday_notice'].includes(i.message_type)||i.sender_type==='system';
 const needsAck=i=>['announcement','attendance_warning'].includes(i.message_type);
 const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="7" width="16" height="13" rx="5"/><path d="M12 3v4M8 12v2m8-2v2m-7 3h6M2 12v4m20-4v4"/><circle cx="12" cy="2.5" r="1"/></svg>';
 function avatar(p){return `<span class="staff-avatar bot-avatar">${p?.profile_image?`<img src="${e(p.profile_image)}" alt="">`:icon}</span>`;}
 function items(){return(alertsLoaded?alertMessages:data.messages||[]).filter(i=>isAlert(i)&&(!properties||properties.includes(String(i.property_id||session.propertyId))));}
 function title(i){if(StaffChat.contractId(i.message))return '근로계약서';if(i.message_type==='announcement')return '공지';if(i.message_type==='attendance_warning')return '근태관리';if(i.message_type==='holiday_approval'||i.message_type==='holiday_notice')return '휴일 신청';if(i.message_type==='attendance_approval')return '출퇴근 수정';if(i.message_type==='property_share_approval')return '지점 공유';return i.sender_label==='근태관리'?'알림':i.sender_label||'알림';}
 function state(i){if(i.is_sender&&needsAck(i)){const a=i.announcement_acknowledgements||[];return `확인 ${a.filter(x=>x.acknowledged_at).length}/${a.length}`;}if(i.approval_status)return ({approved:'승인 완료',rejected:'반려',pending:'승인 대기'})[i.approval_status]||'처리 내역';if(i.acknowledged_at)return '확인 완료';if(needsAck(i))return '확인 필요';if(StaffChat.contractId(i.message))return '계약서 보기';return i.read_at?'읽음':'새 알림';}
 function roomProfiles(){const byId=new Map(profiles.map(p=>[String(p.property_id),p]));for(const i of items()){const id=String(i.property_id||session.propertyId);if(!byId.has(id))byId.set(id,{property_id:id,display_name:'OMS 알림',property_name:''});}return [...byId.values()].filter(p=>!properties||properties.includes(String(p.property_id)));}
 function renderRooms(){if(!session||!$('botRooms'))return;const entries=items(),unread=alertsLoaded?Object.entries(unreadByProperty).filter(([id])=>!properties||properties.includes(id)).reduce((n,[,v])=>n+Number(v),0):entries.filter(i=>!i.is_sender&&!i.read_at).length;const count=$('staffCount');count.textContent=Number(count.dataset.chatUnread||0)+unread||'';
 $('botRooms').innerHTML=roomProfiles().filter(p=>!query||`${p.display_name} ${p.property_name} ${entries.filter(i=>String(i.property_id||session.propertyId)===String(p.property_id)).map(i=>StaffChat.cleanText(i.message)).join(' ')}`.toLowerCase().includes(query)).map(p=>{const list=entries.filter(i=>String(i.property_id||session.propertyId)===String(p.property_id)),last=list[0],n=alertsLoaded?Number(unreadByProperty[p.property_id]||0):list.filter(i=>!i.is_sender&&!i.read_at).length;return `<button type="button" class="hub-room staff-room bot-room ${n?'is-unread':''}" data-bot-property="${e(p.property_id)}">${avatar(p)}<span class="hub-room-copy"><strong>${e(p.display_name)} <small class="bot-label">BOT</small></strong><span class="hub-room-preview">${e(last?StaffChat.cleanText(last.message):'공지와 업무 알림을 전해드립니다.')}</span></span><span class="hub-room-meta"><time>${last?e(new Date(last.created_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})):''}</time><span>${e(p.property_name)}</span>${n?`<b class="hub-count">${n}</b>`:''}</span></button>`;}).join('');
 $('botRooms').querySelectorAll('[data-bot-property]').forEach(b=>b.onclick=()=>open(b.dataset.botProperty));}
 function renderConversation(){if(!$('botConversation')||$('botConversation').hidden)return;const profile=profiles.find(p=>String(p.property_id)===roomProperty),q=$('botSearch').value.trim().toLowerCase();$('botTitle').textContent=announcementMode?'공지':profile?.display_name||'OMS 알림';$('botProperty').textContent=announcementMode?'발송 내역':profile?.property_name||'';$('botNewAnnouncement').hidden=!announcementMode;
 const list=items().filter(i=>announcementMode?i.message_type==='announcement'&&i.is_sender:String(i.property_id||session.propertyId)===roomProperty).filter(i=>!q||`${title(i)} ${StaffChat.cleanText(i.message)}`.toLowerCase().includes(q)).slice().sort((a,b)=>a.created_at.localeCompare(b.created_at));
 const scroller=$('botTimeline'),near=scroller.scrollHeight-scroller.scrollTop-scroller.clientHeight<90,oldTop=scroller.scrollTop;
 $('botTimeline').innerHTML=(hasOlder?'<button type="button" id="botOlder" class="bot-older">이전 알림 더 보기</button>':'')+(list.map(i=>`<article class="bot-message"><div class="bot-message-meta"><b>${e(title(i))}</b><time>${e(new Date(i.created_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</time></div><p>${e(StaffChat.cleanText(i.message))}</p><div class="bot-message-actions"><span class="bot-state ${i.acknowledged_at||i.approval_status==='approved'?'done':''}">${e(state(i))}</span><button type="button" data-bot-message="${e(i.message_id)}">${StaffChat.contractId(i.message)?'계약서 확인':needsAck(i)&&!i.is_sender&&!i.acknowledged_at?'내용 확인':i.approval_status==='pending'?'결재 보기':'상세 보기'} ›</button></div>${i.acknowledged_at?`<small class="bot-ack-time">${e(i.acknowledged_name||'')} · ${e(new Date(i.acknowledged_at).toLocaleString('ko-KR'))} 확인</small>`:''}</article>`).join('')||'<div class="bot-empty">'+(q?'검색 결과가 없습니다.':announcementMode?'발송한 공지가 없습니다.':'아직 받은 알림이 없습니다.')+'</div>');$('botOlder')?.addEventListener('click',()=>loadAlerts(true));
 $('botTimeline').querySelectorAll('[data-bot-message]').forEach(b=>b.onclick=()=>{const item=list.find(i=>i.message_id===b.dataset.botMessage);callbacks.openDetail(item);});
 scroller.scrollTop=near?scroller.scrollHeight:oldTop;
 }
 function open(id,announcements=false){roomProperty=String(id||session.propertyId);announcementMode=announcements;$('botSearch').value='';$('botConversation').hidden=false;document.body.classList.add('bot-open');history.pushState({...history.state,omgBot:true},'',location.href);renderConversation();$('botTimeline').scrollTop=$('botTimeline').scrollHeight;}
 function close(){if(history.state?.omgBot)history.back();else hide();}
 function hide(){$('botConversation').hidden=true;document.body.classList.remove('bot-open');}
 async function refresh(){if(refreshing)return;refreshing=true;const hint=$('pullRefresh');hint.hidden=false;hint.textContent='새로고침 중…';try{await callbacks.refresh();await loadProfiles();hint.textContent='업데이트했습니다.';}catch{hint.textContent='연결을 확인하고 다시 내려주세요.';}finally{refreshing=false;setTimeout(()=>hint.hidden=true,1200);}}
 async function loadProfiles(){try{const {data:v,error}=await omgSupabase.rpc('notification_bot_settings',{p_access_token:session.accessToken,p_action:'list'});if(error||!v?.ok)throw Error('봇 설정을 불러오지 못했습니다.');profiles=v.bots||[];profileLoaded=true;renderRooms();renderConversation();}catch(err){console.warn(err);}}
 async function loadAlerts(older=false){if(alertBusy||!session)return;alertBusy=true;try{const {data:v,error}=await omgSupabase.rpc('list_notification_bot_messages',{p_access_token:session.accessToken,...(older&&cursor?{p_before_at:cursor.created_at,p_before_id:cursor.message_id}:{})});if(error||!v?.ok)throw Error('알림을 불러오지 못했습니다.');const incoming=v.messages||[],map=new Map(alertMessages.map(i=>[i.message_id,i]));incoming.forEach(i=>map.set(i.message_id,i));alertMessages=[...map.values()].sort((a,b)=>b.created_at.localeCompare(a.created_at)||b.message_id.localeCompare(a.message_id));unreadByProperty=v.unread_by_property||{};if(older||!alertsLoaded){cursor=incoming.at(-1);hasOlder=incoming.length===100;}alertsLoaded=true;renderRooms();renderConversation();}catch(err){console.warn(err);}finally{alertBusy=false;}}
 function init(s,c){session=s;callbacks=c;const section=document.createElement('section');section.id='botConversation';section.hidden=true;section.setAttribute('role','dialog');section.setAttribute('aria-modal','true');section.setAttribute('aria-labelledby','botTitle');section.innerHTML='<header class="bot-conversation-head"><button id="botBack" type="button" aria-label="알림 닫기">‹</button><div><h2 id="botTitle">OMS 알림</h2><small id="botProperty"></small></div><button id="botNewAnnouncement" type="button" hidden>공지 작성</button></header><input id="botSearch" type="search" placeholder="알림 내용 검색" aria-label="알림 내용 검색"><div id="botTimeline"></div>';document.body.append(section);$('botBack').onclick=close;$('botSearch').oninput=renderConversation;$('botNewAnnouncement').onclick=()=>callbacks.compose();window.addEventListener('popstate',()=>{if(!history.state?.omgBot)hide();});document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&!section.hidden&&$('detail').hidden&&$('composeOverlay').hidden)close();});
 const hint=document.createElement('div');hint.id='pullRefresh';hint.hidden=true;hint.setAttribute('role','status');document.querySelector('.top').after(hint);let start=null,distance=0;
 document.addEventListener('touchstart',ev=>{start=!refreshing&&window.scrollY<=0&&!document.body.classList.contains('modal-open')&&!document.body.classList.contains('bot-open')&&!document.querySelector('dialog[open]')&&!ev.target.closest('input,textarea,button,.property-picker-panel')&&ev.touches.length===1?{x:ev.touches[0].clientX,y:ev.touches[0].clientY}:null;distance=0;},{passive:true});
 document.addEventListener('touchmove',ev=>{if(!start)return;const t=ev.touches[0];if(Math.abs(t.clientX-start.x)>35){start=null;hint.hidden=true;return;}distance=t.clientY-start.y;if(distance>12&&window.scrollY<=0){ev.preventDefault();hint.hidden=false;hint.textContent=distance>80?'놓으면 새로고침':'아래로 당겨 새로고침';}},{passive:false});
 document.addEventListener('touchend',()=>{if(start&&distance>80)refresh();else if(!refreshing)hint.hidden=true;start=null;distance=0;},{passive:true});document.addEventListener('touchcancel',()=>{start=null;if(!refreshing)hint.hidden=true;});loadProfiles();loadAlerts();
 if(new URLSearchParams(location.search).get('tab')==='alerts')setTimeout(()=>open(session.propertyId),0);
 }
 return {init,isAlert,search(v){query=v.trim().toLowerCase();renderRooms();},update(v,ids){data=v;properties=ids;renderRooms();renderConversation();loadAlerts();},renderRooms,openAnnouncements(){open(session.propertyId,true);}};
})();
