(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const money=v=>v==null?'산정 필요':Number(v).toLocaleString('ko-KR')+'원';
const duration=v=>`${Math.floor(Number(v)/60)}시간${Number(v)%60?' '+Number(v)%60+'분':''}`;
function init({accessToken,getPropertyIds,ownPropertyId}){
const host=document.getElementById('payrollView'),button=document.getElementById('openPayroll'),content=document.getElementById('attendanceContent'),title=document.getElementById('pageTitle');let active=false,version=0,mode='month';
host.innerHTML='<button class="payroll-back" type="button">‹ 근태관리</button><section class="payroll-filter"><div class="payroll-tabs"><button type="button" data-mode="month" aria-pressed="true">월간</button><button type="button" data-mode="range" aria-pressed="false">기간</button></div><div class="payroll-month"><button type="button" data-step="-1" aria-label="이전 달">‹</button><input type="month" aria-label="급여 조회월"><button type="button" data-step="1" aria-label="다음 달">›</button></div><div class="payroll-dates" hidden><label>시작일<input type="date" class="payroll-from"></label><label>종료일<input type="date" class="payroll-to"></label></div><p class="payroll-period"></p></section><p class="payroll-message" role="alert"></p><section class="panel payroll-panel"><h2>급여현황</h2><div class="payroll-columns"><span>이름</span><span>근무시간</span><span>총 급여</span><span></span></div><div class="payroll-results"></div><p class="payroll-help">세전 기본급 예상액입니다. 수당·공제는 포함하지 않습니다. 월급제의 일부 기간은 일할계산 기준이 필요하여 ‘산정 필요’로 표시합니다.</p></section>';
const month=host.querySelector('[type=month]'),from=host.querySelector('.payroll-from'),to=host.querySelector('.payroll-to'),results=host.querySelector('.payroll-results'),message=host.querySelector('.payroll-message');month.value=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).format(new Date());
function monthRange(){const[y,m]=month.value.split('-').map(Number);from.value=month.value+'-01';to.value=month.value+'-'+new Date(y,m,0).getDate();}monthRange();
async function refresh(){if(!active)return;const current=++version;results.replaceChildren();message.textContent='불러오는 중…';try{if(mode==='month'&&!/^\d{4}-\d{2}$/.test(month.value))throw Error('조회월을 선택해주세요.');if(mode==='range'&&(!from.value||!to.value||from.value>to.value))throw Error('시작일과 종료일을 확인해주세요.');host.querySelector('.payroll-period').textContent=mode==='month'?month.value.replace('-','년 ')+'월 · 근무자별 급여주기 기준':from.value+' ~ '+to.value;const args=mode==='month'?{p_month:month.value+'-01'}:{p_from_date:from.value,p_to_date:to.value};const{data,error}=await omgSupabase.rpc(mode==='month'?'list_employee_payroll':'list_employee_payroll_range',{p_access_token:accessToken,p_property_ids:getPropertyIds(),...args});if(current!==version||!active)return;if(error||!data?.ok)throw Error(data?.message||'급여정보를 불러오지 못했습니다. 다시 시도해주세요.');message.textContent='';results.innerHTML=(data.employees||[]).map(x=>`<article class="payroll-result"><button class="payroll-row" type="button" aria-expanded="false"><span class="payroll-person-name"><strong>${esc(x.display_name)}</strong>${x.property_id!==ownPropertyId?`<small title="${esc(x.property_name)}">${esc(x.property_name)}</small>`:''}</span><span class="payroll-hours">${duration(x.work_minutes)}</span><strong class="payroll-amount">${x.pay_type==='hourly'&&x.hourly_rate==null||x.pay_type==='monthly'&&x.monthly_salary==null?'미설정':money(x.expected_pay)}</strong><span class="payroll-arrow">⌄</span></button><div class="payroll-detail" hidden><dl><dt>급여 산정기간</dt><dd>${esc(x.period_start)} ~ ${esc(x.period_end)}</dd><dt>근무시간</dt><dd>${duration(x.work_minutes)} · ${x.work_days}일</dd><dt>급여 기준</dt><dd>${x.pay_type==='monthly'?'월급 '+money(x.monthly_salary):'시급 '+money(x.hourly_rate)}</dd><dt>급여일</dt><dd>${esc(x.pay_date||'미설정')}</dd><dt>총 급여</dt><dd>${money(x.expected_pay)}</dd></dl>${x.expected_pay==null&&x.monthly_salary!=null?'<p class="payroll-warning">급여주기와 일치하지 않는 기간입니다. 월급 일할계산 기준이 필요합니다.</p>':''}${x.missing_count?`<p class="payroll-warning">미기록 ${x.missing_count}건 · 계산에서 제외</p>`:''}${x.working_count?`<p class="payroll-help">근무 중 ${x.working_count}건 · 퇴근 후 반영</p>`:''}</div></article>`).join('')||'<div class="empty">선택한 지점의 근무자가 없습니다.</div>';results.querySelectorAll('.payroll-row').forEach(row=>row.onclick=()=>{const detail=row.nextElementSibling;detail.hidden=!detail.hidden;row.setAttribute('aria-expanded',String(!detail.hidden));row.querySelector('.payroll-arrow').textContent=detail.hidden?'⌄':'⌃';});}catch(e){if(current===version&&active){results.replaceChildren();message.textContent=e.message;}}}
button.hidden=false;button.onclick=()=>{active=true;content.hidden=true;host.hidden=false;button.hidden=true;title.textContent=document.title='급여정보';refresh();};host.querySelector('.payroll-back').onclick=()=>{active=false;version++;host.hidden=true;content.hidden=false;button.hidden=false;title.textContent=document.title='근태관리';window.dispatchEvent(new Event('payrollclosed'));button.focus();};
host.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;host.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));host.querySelector('.payroll-month').hidden=mode!=='month';host.querySelector('.payroll-dates').hidden=mode!=='range';refresh();});month.onchange=()=>{monthRange();refresh();};from.onchange=to.onchange=()=>{to.min=from.value;refresh();};host.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const[y,m]=month.value.split('-').map(Number);if(!y||!m)return;month.value=new Date(Date.UTC(y,m-1+Number(b.dataset.step),1)).toISOString().slice(0,7);monthRange();refresh();});return{isActive:()=>active,refresh};
}window.OMSPayroll={init};})();
