(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const bytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
 async function call(action,data={}){const {data:v,error}=await omgSupabase.rpc('platform_message_storage',{p_action:action,p_data:data});if(error||!v?.ok)throw new Error(v?.message||error?.message||'저장 현황을 확인하지 못했습니다.');return v;}
 async function sweep(id,status){let n=0;while(n++<100){const {data}=await omgSupabase.auth.getSession();if(!data.session)throw new Error('운영자 로그인이 필요합니다.');const r=await fetch(OMG_SUPABASE.url+'/functions/v1/guest-support',{method:'POST',headers:{'Content-Type':'application/json',apikey:OMG_SUPABASE.publishableKey},body:JSON.stringify({action:'cleanup_files',platform_token:data.session.access_token,data:{job_id:id}}),signal:AbortSignal.timeout(40000)});const v=await r.json();if(!r.ok||!v.ok)throw new Error(v.message||'파일 정리에 실패했습니다. 다시 시도해주세요.');if(v.status==='complete')return;status.textContent=`첨부파일 정리 중… ${n*50}개 처리`; }throw new Error('일부 파일이 남았습니다. 정리 계속을 눌러주세요.');}
 const root=document.createElement('section');root.className='panel storage-panel';root.innerHTML='<div class="panel-head"><h2>지점별 저장 사용량</h2><button class="refresh storage-refresh" type="button">새로고침</button></div><p class="storage-note">대화·메세지 본문 용량과 실제 첨부파일 용량입니다. DB 인덱스·백업·시스템 공간은 제외합니다.</p><div class="storage-status" role="status"></div><div class="storage-list"></div>';
 document.querySelector('#operatorShell .summary').after(root);const status=root.querySelector('.storage-status'),list=root.querySelector('.storage-list');
 async function load(){try{status.textContent='사용량을 불러오는 중입니다.';const v=await call('usage');list.innerHTML=v.properties.map(p=>`<article class="storage-property" data-property="${p.property_id}"><div class="storage-heading"><b>${esc(p.property_name)}</b><strong>${bytes(Number(p.chat_bytes)+Number(p.message_bytes)+Number(p.chat_photo_bytes)+Number(p.guide_bytes))}</strong></div><div class="storage-metrics"><span>대화 <b>${p.chat_count}건 · ${bytes(+p.chat_bytes)}</b></span><span>메세지 <b>${p.message_count}건 · ${bytes(+p.message_bytes)}</b></span><span>대화 사진 <b>${p.chat_photo_count}개 · ${bytes(+p.chat_photo_bytes)}</b></span><span>메세지 사진 <b>0개 · 0 B</b></span></div><p class="storage-note">안내 첨부 ${bytes(+p.guide_bytes)} · 메세지 사진 첨부는 현재 미지원</p><details class="storage-clean"><summary>과거 내역 정리</summary><div class="storage-choices"><label>보관 기간<select class="storage-months"><option value="3">3개월 이전</option><option value="6">6개월 이전</option><option value="9">9개월 이전</option><option value="12">12개월 이전</option></select></label><div class="storage-categories"><label><input type="checkbox" value="chat">대화</label><label><input type="checkbox" value="messages">메세지</label><label><input type="checkbox" value="chat_photos">대화 사진</label><label><input type="checkbox" value="message_photos" disabled>메세지 사진</label></div></div><button type="button" class="storage-preview">삭제 대상 확인</button><div class="storage-preview-result" role="status"></div></details>${v.pending_jobs.filter(j=>j.property_id===p.property_id).map(j=>`<button type="button" class="storage-resume" data-job="${j.id}">중단된 사진 정리 계속</button>`).join('')}</article>`).join('');status.textContent='';
 list.querySelectorAll('.storage-property').forEach(card=>{const output=card.querySelector('.storage-preview-result');card.querySelectorAll('select,input').forEach(x=>x.onchange=()=>output.replaceChildren());card.querySelector('.storage-preview').onclick=async e=>{e.target.disabled=true;try{const data={property_id:card.dataset.property,months:+card.querySelector('select').value,categories:[...card.querySelectorAll('input:checked')].map(x=>x.value)};if(!data.categories.length)throw new Error('정리할 항목을 선택해주세요.');const preview=await call('preview',data),s=preview.summary,total=+s.chat_count+(+s.message_count)+(+s.chat_photo_count);if(!total){output.textContent='선택한 기간에 삭제할 내역이 없습니다.';return;}
 output.innerHTML=`<p><b>${esc(s.property_name)}</b><br>${esc(new Date(s.cutoff).toLocaleString('ko-KR'))} 이전<br>대화 ${s.chat_count}건 · 메세지 ${s.message_count}건<br>사진 ${s.chat_photo_count}개 · ${bytes(+s.photo_bytes)}</p><p>선택한 내역은 복구할 수 없습니다. 안내 사진과 최근 기록은 유지됩니다.</p><label>확인을 위해 숙소명 입력<input class="storage-confirm-name" autocomplete="off" placeholder="${esc(s.property_name)}"></label><button type="button" class="storage-execute" disabled>선택한 과거 내역 삭제</button>`;
 const confirm=output.querySelector('.storage-execute'),name=output.querySelector('input');name.oninput=()=>confirm.disabled=name.value!==s.property_name;confirm.onclick=async()=>{confirm.disabled=true;name.disabled=true;try{const job=await call('execute',{job_id:preview.job_id,confirm_name:name.value});status.textContent='선택한 내역을 정리하고 있습니다…';if(job.status==='pending')await sweep(job.job_id,status);await load();status.textContent='선택한 과거 내역을 정리했습니다.';}catch(err){status.textContent=err.message;await load().catch(()=>{});status.textContent=err.message;}};
 }catch(err){output.textContent=err.message;}finally{e.target.disabled=false;}};});
 list.querySelectorAll('[data-job]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await sweep(b.dataset.job,status);await load();status.textContent='사진 정리를 완료했습니다.';}catch(e){status.textContent=e.message;b.disabled=false;}});
 }catch(e){status.textContent=e.message;}}
 root.querySelector('.storage-refresh').onclick=load;window.addEventListener('load',load);
})();
