(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const bytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
 const total=p=>['chat_bytes','message_bytes','chat_photo_bytes','guide_bytes','attendance_bytes'].reduce((n,k)=>n+Number(p[k]||0),0);

 function dialog({title,text,html='',confirm='확인',danger=false,cancel=true,onReady}){
  return new Promise(resolve=>{
   const layer=document.createElement('div');layer.className='storage-modal-layer';
   layer.innerHTML=`<div class="storage-modal" role="dialog" aria-modal="true" aria-labelledby="storageDialogTitle"><div class="storage-modal-icon ${danger?'danger':''}">${danger?'!':'✓'}</div><h3 id="storageDialogTitle">${esc(title)}</h3>${text?`<p>${esc(text)}</p>`:''}${html}<div class="storage-modal-actions">${cancel?'<button type="button" class="storage-modal-cancel">취소</button>':''}<button type="button" class="storage-modal-confirm ${danger?'danger':''}">${esc(confirm)}</button></div></div>`;
   document.body.append(layer);const finish=value=>{layer.remove();resolve(value)};
   layer.querySelector('.storage-modal-cancel')?.addEventListener('click',()=>finish(false));
   layer.querySelector('.storage-modal-confirm').addEventListener('click',()=>finish(onReady?onReady(layer):true));
   layer.addEventListener('click',e=>{if(e.target===layer&&cancel)finish(false)});layer.querySelector('input')?.focus();
  });
 }

 function createManager({host,ownerToken=null}){
  host.innerHTML='<p class="storage-note">대화·메세지·출퇴근 기록과 실제 첨부파일 용량입니다. DB 인덱스·백업·시스템 공간은 제외합니다.</p><div class="storage-status" role="status"></div><div class="storage-list"></div>';
  const status=host.querySelector('.storage-status'),list=host.querySelector('.storage-list');
  async function call(action,data={}){const args=ownerToken?{p_access_token:ownerToken,p_action:action,p_data:data}:{p_action:action,p_data:data};const {data:v,error}=await omgSupabase.rpc(ownerToken?'owner_message_storage':'platform_message_storage',args);if(error||!v?.ok)throw new Error(v?.message||error?.message||'저장 현황을 확인하지 못했습니다.');return v;}
  async function sweep(id){let n=0;while(n++<100){let auth={access_token:ownerToken};if(!ownerToken){const {data}=await omgSupabase.auth.getSession();auth=data.session||{};if(!auth.access_token)throw new Error('운영자 로그인이 필요합니다.');}const body={action:'cleanup_files',data:{job_id:id},[ownerToken?'access_token':'platform_token']:auth.access_token};const r=await fetch(OMG_SUPABASE.url+'/functions/v1/guest-support',{method:'POST',headers:{'Content-Type':'application/json',apikey:OMG_SUPABASE.publishableKey},body:JSON.stringify(body),signal:AbortSignal.timeout(40000)}),v=await r.json();if(!r.ok||!v.ok)throw new Error(v.message||'파일 정리에 실패했습니다. 다시 시도해주세요.');if(v.status==='complete')return;status.textContent=`첨부파일 정리 중… ${n*50}개 처리`;}throw new Error('일부 파일이 남았습니다. 정리 계속을 눌러주세요.');}
  function cardMarkup(p,pending){return `<article class="storage-property" data-property="${p.property_id}"><div class="storage-heading"><b>${esc(p.property_name)}</b><strong>${bytes(total(p))}</strong></div><div class="storage-metrics"><span>대화 <b>${p.chat_count}건 · ${bytes(+p.chat_bytes)}</b></span><span>메세지 <b>${p.message_count}건 · ${bytes(+p.message_bytes)}</b></span><span>대화 사진 <b>${p.chat_photo_count}개 · ${bytes(+p.chat_photo_bytes)}</b></span><span>출퇴근 기록 <b>${p.attendance_count}건 · ${bytes(+p.attendance_bytes)}</b></span></div><p class="storage-note">안내 첨부 ${bytes(+p.guide_bytes)} · 메세지 사진 첨부는 현재 미지원</p><details class="storage-clean"><summary>과거 내역 정리</summary><div class="storage-choices"><label>보관 기간<select class="storage-months"><option value="3">3개월 이전</option><option value="6">6개월 이전</option><option value="9">9개월 이전</option><option value="12">12개월 이전</option><option value="custom">직접 기간 설정</option></select></label><div class="storage-date-range" hidden><label>시작일<input class="storage-start" type="date"></label><label>종료일<input class="storage-end" type="date" max="${new Date().toISOString().slice(0,10)}"></label></div><div class="storage-categories"><label><input type="checkbox" value="chat">대화</label><label><input type="checkbox" value="messages">메세지</label><label><input type="checkbox" value="chat_photos">대화 사진</label><label><input type="checkbox" value="attendance">출퇴근 기록</label><label><input type="checkbox" value="message_photos" disabled>메세지 사진</label></div></div><button type="button" class="storage-preview">삭제실행</button></details>${pending.map(j=>`<button type="button" class="storage-resume" data-job="${j.id}">중단된 사진 정리 계속</button>`).join('')}</article>`;}
  async function execute(card,button){button.disabled=true;try{const period=card.querySelector('.storage-months').value,data={property_id:card.dataset.property,period_mode:period==='custom'?'custom':'preset',categories:[...card.querySelectorAll('.storage-categories input:checked')].map(x=>x.value)};if(period==='custom'){data.start_date=card.querySelector('.storage-start').value;data.end_date=card.querySelector('.storage-end').value;}else data.months=+period;if(!data.categories.length)throw new Error('정리할 항목을 선택해주세요.');const preview=await call('preview',data),s=preview.summary,totalCount=+s.chat_count+(+s.message_count)+(+s.chat_photo_count)+(+s.attendance_count);if(!totalCount){await dialog({title:'삭제할 내역이 없습니다',text:'선택한 기간과 항목에 해당하는 내역이 없습니다.',cancel:false});return;}const periodText=s.range_start?`${new Date(s.range_start).toLocaleDateString('ko-KR')} ~ ${new Date(new Date(s.cutoff)-86400000).toLocaleDateString('ko-KR')}`:`${new Date(s.cutoff).toLocaleDateString('ko-KR')} 이전`;const html=`<div class="storage-confirm-summary"><b>${esc(s.property_name)}</b><span>${esc(periodText)}</span><span>대화 ${s.chat_count}건 · 메세지 ${s.message_count}건</span><span>사진 ${s.chat_photo_count}개 · 출퇴근 기록 ${s.attendance_count}건</span></div><p class="storage-warning">삭제한 내역은 복구할 수 없습니다.</p><label class="storage-confirm-label">확인을 위해 숙소명을 입력해주세요.<input class="storage-confirm-name" autocomplete="off" placeholder="${esc(s.property_name)}"></label>`;const name=await dialog({title:'내역을 삭제할까요?',html,confirm:'확인',danger:true,onReady:layer=>layer.querySelector('.storage-confirm-name').value});if(name===false)return;if(name!==s.property_name)throw new Error(`숙소명 “${s.property_name}”을 정확히 입력해주세요.`);status.textContent='선택한 내역을 정리하고 있습니다…';const job=await call('execute',{job_id:preview.job_id,confirm_name:name});if(job.status==='pending')await sweep(job.job_id);await load();await dialog({title:'삭제되었습니다',text:'선택한 기간의 내역 정리를 완료했습니다.',cancel:false});}catch(err){status.textContent=err.message;}finally{button.disabled=false;}}
  async function load(){try{status.textContent='사용량을 불러오는 중입니다.';const v=await call('usage');list.innerHTML=v.properties.map(p=>cardMarkup(p,v.pending_jobs.filter(j=>j.property_id===p.property_id))).join('');status.textContent='';list.querySelectorAll('.storage-property').forEach(card=>{const period=card.querySelector('.storage-months'),range=card.querySelector('.storage-date-range');period.onchange=()=>range.hidden=period.value!=='custom';card.querySelector('.storage-preview').onclick=e=>execute(card,e.currentTarget);});list.querySelectorAll('[data-job]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await sweep(b.dataset.job);await load();await dialog({title:'정리가 완료되었습니다',text:'남아 있던 첨부파일까지 모두 정리했습니다.',cancel:false});}catch(e){status.textContent=e.message;b.disabled=false;}});}catch(e){status.textContent=e.message;}}
  load();return {load};
 }
 window.PropertyDataManagement={mount({host,accessToken}){return createManager({host,ownerToken:accessToken});}};
 const shell=document.querySelector('#operatorShell .summary');if(shell){const root=document.createElement('section');root.className='panel storage-panel';root.innerHTML='<div class="panel-head"><h2>지점별 저장 사용량</h2><button class="refresh storage-refresh" type="button">새로고침</button></div><div class="storage-host"></div>';shell.after(root);const manager=createManager({host:root.querySelector('.storage-host')});root.querySelector('.storage-refresh').onclick=manager.load;}
})();
