window.ReportInbox=(()=>{
 let session,rows=[],visible=false,busy=false,timer,query='',cursor=null,paged=false,detailSequence=0;
 const $=id=>document.getElementById(id),e=value=>GuestSupport.esc(value),label=type=>type==='clock_in'?'출근보고':'퇴근보고';
 async function call(args={}){const {data,error}=await window.omgSupabase.rpc('work_report_inbox',{p_access_token:session.accessToken,...args});if(error||!data?.ok)throw new Error(data?.message||'보고를 불러오지 못했습니다.');return data;}
 function render(){const items=rows.filter(r=>`${label(r.report_type)} ${r.employee_name} ${r.property_name} ${r.preview}`.toLowerCase().includes(query));$('reportRows').innerHTML=items.map(r=>`<button class="hub-room report-row" data-report="${e(r.report_id)}" type="button">${StaffChat.avatar(r.employee_name,r.profile_image)}<span class="hub-room-copy"><strong>${e(label(r.report_type)+' '+r.employee_name)}</strong><span class="hub-room-preview">${e(r.property_name)}${r.edited?' · 수정됨':''}</span></span><span class="hub-room-meta"><time>${e(new Date(r.submitted_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</time><span aria-hidden="true">›</span></span></button>`).join('')||'<div class="empty">'+(query?'검색 결과가 없습니다.':'제출한 보고가 없습니다.')+'</div>';$('reportRows').querySelectorAll('[data-report]').forEach(button=>button.onclick=()=>open(button.dataset.report));}
 async function load(older=false){if(!session||busy||!visible||document.hidden)return;busy=true;clearTimeout(timer);try{const data=await call(older&&cursor?{p_before_at:cursor.submitted_at,p_before_id:cursor.report_id}:{});if(older)paged=true;const map=new Map((older||paged?rows:[]).map(r=>[r.report_id,r]));data.reports.forEach(r=>map.set(r.report_id,r));rows=[...map.values()].sort((a,b)=>b.submitted_at.localeCompare(a.submitted_at)||b.report_id.localeCompare(a.report_id));if(older||!paged){cursor=data.reports.at(-1);$('reportOlder').hidden=data.reports.length<50;}$('reportError').textContent='';render();}catch(err){console.warn('Report inbox load',err);$('reportError').textContent='데이터를 불러오는 중입니다.';}finally{busy=false;if(visible)timer=setTimeout(load,10000);}}
 function photo(value){return typeof value==='string'&&value.length<=1100000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(value);}
 function content(payload){if(!Array.isArray(payload.report_fields))return `<p class="report-text">${e(payload.text||'보고 내용이 없습니다.')}</p>`;return payload.report_fields.map(field=>{const value=field.kind==='photo'?payload[field.key]:field.value;let result=field.kind==='photo'?(photo(value)?`<img class="report-photo" src="${e(value)}" alt="${e(field.label)}">`:'없음'):typeof value==='object'&&value&&!Array.isArray(value)?e(`${value.count||0}개 · ${(value.rooms||[]).join(', ')||'객실 미선택'}`):e(Array.isArray(value)?value.join(', ')||'없음':value??'없음');return `<div class="report-value-row"><strong>${e(field.label)}</strong><div>${result}</div></div>`;}).join('')+(Array.isArray(payload.reminder_cards_acknowledged)?`<div class="report-value-row"><strong>리마인더 확인</strong><div>${payload.reminder_cards_acknowledged.length}개</div></div>`:'')+`<div class="report-value-row"><strong>특이사항</strong><div>${e(payload.memo||'없음')}</div></div>`;}
 async function open(id){const seq=++detailSequence,dialog=$('reportDetail');$('reportDetailBody').textContent='데이터를 불러오는 중입니다.';if(!dialog.open){dialog.showModal();history.pushState({...history.state,reportDetail:true},'',location.href);}try{const r=(await call({p_report_id:id})).reports[0];if(seq!==detailSequence||!dialog.open)return;if(!r)throw new Error('보고를 찾을 수 없습니다.');$('reportDetailTitle').textContent=label(r.report_type)+' '+r.employee_name;$('reportDetailMeta').textContent=r.property_name+' · '+new Date(r.submitted_at).toLocaleString('ko-KR');$('reportDetailBody').innerHTML=content(r.payload||{});}catch(err){if(seq===detailSequence)$('reportDetailBody').textContent=err.message;}}
 function close(){detailSequence++;$('reportDetail').close();if(history.state?.reportDetail)history.back();}
 return {init(s,nav){session=s;const pane=document.createElement('section');pane.id='reportPane';pane.hidden=true;pane.innerHTML='<div id="reportError" role="status"></div><div id="reportRows"></div><button id="reportOlder" class="btn" type="button" hidden>이전 보고 더 보기</button>';nav.after(pane);const dialog=document.createElement('dialog');dialog.id='reportDetail';dialog.innerHTML='<div class="report-detail-top"><h2 id="reportDetailTitle">보고</h2><button id="reportDetailClose" type="button" aria-label="닫기">×</button></div><p id="reportDetailMeta"></p><div id="reportDetailBody"></div>';document.body.append(dialog);$('reportDetailClose').onclick=close;dialog.addEventListener('cancel',event=>{event.preventDefault();close();});dialog.onclick=event=>{if(event.target===dialog)close();};$('reportOlder').onclick=()=>load(true);addEventListener('popstate',()=>{if(dialog.open&&!history.state?.reportDetail){detailSequence++;dialog.close();}});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&visible)load();});addEventListener('pagehide',()=>clearTimeout(timer));},show(value){visible=value;$('reportPane').hidden=!value;clearTimeout(timer);if(value)load();},search(value){query=value.trim().toLowerCase();render();},load};
})();
