(async()=>{
 const $=id=>document.getElementById(id),e=GuestSupport.esc,peer=new URLSearchParams(location.search).get('peer');let session,messages=[],busy=false,sending=false,timer,delay=2000,priority='normal',pending=null,started=false;
 const line=$('timeline'),input=$('body');let draftKey='';
 const call=(a,d={})=>StaffChat.call(session,a,{peer,...d});
 function status(t='',bad=false){$('status').textContent=t;$('status').className='status'+(bad?' error':'');}
 function keepDraft(){try{sessionStorage.setItem(draftKey,JSON.stringify({body:input.value,priority,pending}));}catch{}}
 function render(older=false){const near=line.scrollHeight-line.scrollTop-line.clientHeight<110,prev=line.scrollHeight;let day='';$('bubbles').innerHTML=messages.map(m=>{const d=new Date(m.created_at).toLocaleDateString('ko-KR'),label=d!==day?`<div class="day">${e(d)}</div>`:'';day=d;return label+`<div class="bubble-row ${m.mine?'mine':''}" data-id="${e(m.id)}">${m.priority==='urgent'?'<span class="staff-urgent">긴급</span>':''}${m.broadcast?'<span class="staff-broadcast">여러 사람에게 보낸 메세지</span>':''}<div class="bubble">${e(m.body)}</div><div class="bubble-time">${e(new Date(m.created_at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}))}</div></div>`;}).join('')||'<div class="empty">첫 메세지를 보내 대화를 시작하세요.</div>';if(older)line.scrollTop+=line.scrollHeight-prev;else if(near||!started)line.scrollTop=line.scrollHeight;started=true;}
 async function markRead(){const ids=messages.filter(m=>!m.mine&&!m.read_at).map(m=>m.id);if(ids.length&&!document.hidden){await call('read',{ids});messages.forEach(m=>{if(ids.includes(m.id))m.read_at=new Date().toISOString();});}}
 async function load(older=false){if(busy||document.hidden)return;busy=true;clearTimeout(timer);try{const last=messages.at(-1),first=messages[0];const v=await call('messages',older&&first?{before_time:first.created_at,before_id:first.id}:last?{after_time:last.created_at,after_id:last.id}:{});$('roomTitle').textContent=v.peer.display_name;$('peerAvatar').innerHTML=StaffChat.avatar(v.peer.display_name,v.peer.profile_image);$('send').disabled=!v.can_send||sending;input.disabled=!v.can_send;if(!v.can_send)status('현재 이 계정에 메세지를 보낼 수 없습니다.',true);const map=new Map(messages.map(m=>[m.id,m]));v.messages.forEach(m=>map.set(m.id,m));messages=[...map.values()].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));if(older||!started)$('older').hidden=v.messages.length<50;if(v.messages.length||!started)render(older);await markRead();delay=!older&&v.messages.length===50?50:2000;}catch(err){status(err.message,true);delay=Math.min(delay*2,30000);}finally{busy=false;timer=setTimeout(load,delay);}}
 $('older').onclick=()=>load(true);
 $('priority').onclick=()=>{priority=priority==='urgent'?'normal':'urgent';$('priority').textContent=priority==='urgent'?'긴급⌄':'일반⌄';$('priority').setAttribute('aria-pressed',String(priority==='urgent'));$('modeHint').textContent=priority==='urgent'?'긴급 알림으로 전달됩니다':'메세지를 입력하세요';keepDraft();};
 input.oninput=()=>{input.style.height='auto';input.style.height=Math.min(110,input.scrollHeight)+'px';keepDraft();};
 $('composer').onsubmit=async event=>{event.preventDefault();const body=input.value.trim();if(!body||sending)return;sending=true;$('send').disabled=true;status('보내는 중…');if(!pending||pending.body!==body||pending.priority!==priority)pending={body,priority,client_id:crypto.randomUUID()};keepDraft();try{const result=await call('send',pending);if(input.value.trim()===body)input.value='';pending=null;keepDraft();status('');try{if(!result.duplicate)await window.omgNotifications.send(session.accessToken,result.message_id);}catch{status('메세지는 저장됐지만 알림 전달을 확인하지 못했습니다.',true);}await load();}catch(err){status(err.message,true);}finally{sending=false;$('send').disabled=input.disabled;input.style.height='auto';}};
 document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden)load();});addEventListener('online',()=>load());addEventListener('pagehide',()=>{clearTimeout(timer);keepDraft();});
 try{session=await omgSession.require({allowCompleted:true});if(!session)return;if(!/^(owner|employee):[0-9a-f-]{36}$/i.test(peer||''))throw new Error('대화 상대를 선택해주세요.');draftKey='staff-chat:'+session.accessToken+':'+peer;try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(draft){input.value=draft.body||'';pending=draft.pending;if(draft.priority==='urgent')$('priority').click();}}catch{}await load();}catch(err){status(err.message,true);$('send').disabled=true;}
})();
