const {chromium}=require('playwright');const fs=require('fs');const assert=require('assert/strict');
const dir=require('node:os').tmpdir();const base=process.env.BOT_TEST_URL||'http://127.0.0.1:8765/';
const fixture=`
const pid='11111111-1111-4111-8111-111111111111',pid2='22222222-2222-4222-8222-222222222222';
window.__calls=[];window.__owner=!location.search.includes('stafftest');
window.__session={accessToken:'test-token',sessionKind:window.__owner?'owner':'staff',propertyId:pid,employeeId:'33333333-3333-4333-8333-333333333333'};
window.__items=[{message_id:'m1',property_id:pid,message:'문정국님, 예정시간보다 15분 늦었습니다. 확인해주세요.',message_type:'attendance_warning',sender_type:'system',sender_label:'근태관리',created_at:'2026-10-10T11:00:00Z',is_sender:false,read_at:null,acknowledged_at:null},{message_id:'m2',property_id:pid,message:'내일부터 새 청소 기준을 적용합니다.',message_type:'announcement',sender_type:'owner',sender_label:'사장님',created_at:'2026-10-10T10:00:00Z',is_sender:window.__owner,read_at:null,recipient_labels:['문정국'],announcement_acknowledgements:[{employee_name:'문정국',acknowledged_at:null}]},{message_id:'m3',property_id:pid2,message:'다른 지점 알림',message_type:'holiday_notice',sender_type:'system',sender_label:'근태관리',created_at:'2026-10-09T10:00:00Z',is_sender:false,read_at:null}];
window.__bots=[{property_id:pid,property_name:'One Minute',display_name:'OMS 알림',profile_image:null,alert_mode:'normal'},{property_id:pid2,property_name:'Seoulnest',display_name:'서울 알림',profile_image:null,alert_mode:'normal'}];
const employees=['문정국','변지훈','정준하','신옥재','니완','김민수'].map((display_name,i)=>({employee_id:'e'+i,display_name,contact_phone:'0101234000'+i,scheduled_clock_in:'14:00',scheduled_clock_out:'19:00',job_title:i?'':'매니저'}));
window.__config={can_manage:true,property:{property_id:pid},employees,administrators:[{owner_id:'o1',display_name:'사장',is_current:true}]};
window.omgSession={require:async()=>window.__session};
window.omgTransition={ready:()=>{document.documentElement.classList.remove('omg-booting');}};
window.omgSupabase={rpc:async(name,args)=>{__calls.push({name,args});let v={ok:true};
if(name==='list_property_messages')v={ok:true,can_manage:__owner,messages:__items,recipients:employees.map(x=>({...x,property_id:pid,recipient_key:'employee:'+x.employee_id,recipient_type:'staff'})),unread_count:2};
if(name==='list_notification_bot_messages')v={ok:true,messages:__items,unread_by_property:Object.fromEntries([pid,pid2].map(p=>[p,__items.filter(i=>i.property_id===p&&!i.is_sender&&!i.read_at).length]))};if(name==='notification_bot_settings'){if(args.p_action==='list')v={ok:true,bots:__bots};else{let b=__bots.find(x=>x.property_id===args.p_property_id)||__bots[0];if(args.p_action==='save')Object.assign(b,args.p_data);v={ok:true,bot:b};}}
if(name==='acknowledge_announcement'){if(args.p_understood&&args.p_employee_name==='문정국'){const item=__items.find(x=>x.message_id===args.p_message_id);item.acknowledged_at=new Date().toISOString();item.read_at=item.acknowledged_at;item.acknowledged_name='문정국';}else v={ok:false,message:'본인 이름과 체크를 확인해주세요.'};}
if(name==='mark_property_message_read')__items.find(x=>x.message_id===args.p_message_id).read_at=new Date().toISOString();
if(name==='list_property_shares')v={ok:true,properties:[{property_id:pid,management_number:1},{property_id:pid2,management_number:2}]};
if(name==='work_report_inbox')v={ok:true,reports:[],unread_count:0};
if(name==='get_employee_account_pay')v={ok:true,employees:[]};
if(name==='staff_chat_peer_profile')v={ok:true,profile:{display_name:'문정국',property_name:'One Minute'}};
if(name==='staff_chat_rpc'){const a=args.p_action,d=args.p_data||{};if(a==='rooms')v={ok:true,rooms:[{peer:'employee:33333333-3333-4333-8333-333333333333',name:'문정국',property_id:pid,property_name:'One Minute',preview:'네 알겠습니다.',updated_at:'2026-10-10T12:00:00Z',unread:1}]};else if(a==='messages')v={ok:true,can_send:true,peer:{display_name:'문정국'},messages:d.before_time?[{id:'old',body:'이전 청소 안내',created_at:'2026-09-01T10:00:00Z',mine:true}]:d.after_time?[]:[{id:'now',body:'오늘 청소를 완료했습니다.',created_at:'2026-10-10T10:00:00Z',mine:true}]};}
return {data:v};}};
window.GuestSupport={esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),call:async()=>({rooms:[],properties:[{id:pid,name:'One Minute'},{id:pid2,name:'Seoulnest'}],accounts:[]})};
window.omgPropertySelector={mountStatic:o=>{o.host.innerHTML='<button class="property-picker-button">All ⌄</button>';window.__setProperties=o.onChange;},mountPropertySingle:async o=>({properties:[{property_id:pid}],setItems(){}})};
window.omgWorkConfig={load:async()=>__config,loadEmployeeAttendanceSettings:async()=>({settings:[]}),loadAttendanceWarnings:async()=>({rules:[]})};
window.omgWarningTargets={mount(){},mountConditions(){}};
`;
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];
await context.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base))return route.fulfill({contentType:'application/javascript',body:''});const path=new URL(url).pathname.slice(1);if(path==='supabase-client.js')return route.fulfill({contentType:'application/javascript',body:fixture});if(['guest-support-client.js','property-selector.js','work-config.js','warning-targets.js'].includes(path))return route.fulfill({contentType:'application/javascript',body:''});return route.continue();});
const page=await context.newPage();page.on('pageerror',err=>errors.push(err.message));await page.goto(base+'messages.html?tab=staff');await page.waitForSelector('.bot-room');
assert.equal(await page.locator('[data-hub=alerts]').count(),0);assert.equal(await page.locator('#refresh').count(),0);assert.equal(await page.locator('#announcementButton').isVisible(),true);assert.equal(await page.locator('#composeToggle').isVisible(),true);assert.equal(await page.locator('#staffCount').innerText(),'3');
assert.equal(await page.locator('.bot-room').count(),1);assert.equal(await page.locator('#staffRooms > .staff-room').first().getAttribute('data-bot-property'),null);await page.evaluate(()=>{__items[0].created_at='2026-10-11T12:00:00Z';NotificationBot.renderRooms();});assert.ok(await page.locator('#staffRooms > .staff-room').first().getAttribute('data-bot-property'));await page.screenshot({path:dir+'/bot-messages.png'});
await page.locator('.bot-room').first().click();await page.locator('[data-bot-message=m1]').click();assert.equal(await page.locator('#close').isVisible(),false);await page.locator('#understood').check();await page.locator('#ackName').fill('문정국');await page.locator('#ack').click();await page.waitForFunction(()=>document.getElementById('detail').hidden);assert.match(await page.locator('#botTimeline').innerText(),/확인 완료/);await page.screenshot({path:dir+'/bot-thread.png'});await page.locator('#botBack').click();await page.waitForFunction(()=>document.getElementById('botConversation').hidden);
await page.evaluate(()=>__setProperties(['22222222-2222-4222-8222-222222222222']));assert.equal(await page.locator('.bot-room').count(),1);assert.match(await page.locator('.bot-room').innerText(),/OMS 알림/);
await page.locator('.bot-room').click();assert.match(await page.locator('#botTimeline').innerText(),/Seoulnest/);await page.locator('#botBack').click();await page.waitForFunction(()=>document.getElementById('botConversation').hidden);await page.locator('[data-hub=guest]').click();assert.equal(await page.locator('#composeToggle').isVisible(),false);
await page.goto(base+'staff-management.html');await page.waitForSelector('.bot-settings-card',{state:'attached'});assert.equal(await page.locator('.employee-account:visible').count(),5);assert.equal(await page.locator('#botSettingsHost').isVisible(),false);assert.equal(await page.locator('#employeeMore').isVisible(),true);await page.locator('#addEmployee').click();assert.equal(await page.locator('.employee-account:visible').count(),6);
await page.goto(base+'staff-management.html?view=employees');await page.waitForSelector('.bot-settings-card');assert.equal(await page.locator('#botSettingsHost').isVisible(),true);assert.deepEqual(await page.locator('.bot-settings-card .profile-preview').evaluate(el=>[el.getBoundingClientRect().width,el.getBoundingClientRect().height]),await page.locator('.employee-account .profile-preview').first().evaluate(el=>[el.getBoundingClientRect().width,el.getBoundingClientRect().height]));await page.locator('.bot-settings-card .employee-toggle').click();await page.locator('.bot-settings-card').scrollIntoViewIfNeeded();await page.locator('[data-mode=strong]').click();await page.locator('.bot-save').click();assert.match(await page.locator('.bot-settings-actions').innerText(),/저장했습니다/);await page.screenshot({path:dir+'/bot-settings.png'});
await page.goto(base+'staff-chat.html?peer=employee:33333333-3333-4333-8333-333333333333');await page.waitForSelector('.bubble-row');await page.locator('#chatSearchToggle').click();await page.locator('#chatSearchInput').fill('청소');await page.locator('#chatSearchRun').click();await page.waitForFunction(()=>document.querySelectorAll('.search-match').length===2);await page.locator('#chatSearchPrev').click();assert.match(await page.locator('.search-current').innerText(),/이전 청소/);await page.screenshot({path:dir+'/chat-search.png'});
await page.goto(base+'messages.html?tab=staff&stafftest=1&message_id=m1');await page.waitForSelector('#announcementConfirm:visible');assert.equal(await page.locator('#announcementButton').isVisible(),false);assert.equal(await page.locator('[data-hub=approvals]').isVisible(),false);
console.log(JSON.stringify({errors,result:'PASS: role tabs, bot unread count, property filtering, required acknowledgement, five-person limit, inline add, bot settings save, historical chat search, direct alert popup'}));assert.deepEqual(errors,[]);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
