const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(f,'utf8'),tick=()=>new Promise(r=>setTimeout(r,30));
function page(f,url){const html=read(f),dom=new JSDOM(html.replace(/<script[\s\S]*?<\/script>/g,''),{url,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.omgTransition={ready(){}};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};return{dom,w,html};}
function inline(w,html){for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(m[1].trim())w.eval(m[1]+(m[1].includes("employeeConfigs={}")?";window.testConfigs=()=>employeeConfigs;window.testSync=syncCurrent;":""));}
(async()=>{
 let {dom,w,html}=page('owner-settings.html','https://omgworks24.com/owner-settings.html');w.eval(read('work-config.js'));w.eval(read('property-selector.js'));w.eval(read('select-picker.js'));const cfg={ok:true,can_manage:true,property:{name:'Test',business_type:'lodging',rooms:['101'],room_types:[{name:'Room',rooms:['101']}],custom_report_fields:[{key:'custom_first',label:'First',kind:'text',size:'full',required:false},{key:'custom_second',label:'Second',kind:'text',size:'half',required:true}]},employees:[{employee_id:'e1',display_name:'One',report_config:{clock_in:[],clock_out:[],reminder_cards:[]}},{employee_id:'e2',display_name:'Two',report_config:{clock_in:[],clock_out:[],reminder_cards:[]}}]};w.omgSession={require:async()=>({accessToken:'x',sessionKind:'owner'})};w.omgWorkConfig.load=async()=>cfg;w.omgSupabase={rpc:async()=>({data:{ok:true,properties:[]}})};inline(w,html);await tick();
 const checkbox=key=>w.document.querySelector(`input[data-type][value="${key}"]`),toggle=key=>{const c=checkbox(key);c.checked=!c.checked;c.dispatchEvent(new w.Event('change'));};assert.equal(checkbox('inspect_rooms'),null);toggle('custom_first');toggle('custom_second');assert.deepEqual(Array.from(w.testConfigs().e1.clock_in),['custom_first','custom_second']);assert.equal(checkbox('custom_first').nextElementSibling.querySelector('small').textContent,'1');toggle('custom_first');toggle('custom_first');assert.deepEqual(Array.from(w.testConfigs().e1.clock_in),['custom_second','custom_first']);
 const input=w.document.getElementById('customFieldName'),add=w.document.getElementById('addCustomField');input.value='Count';input.dispatchEvent(new w.Event('input'));assert(add.disabled);const choose=(host,value)=>{const radio=w.document.querySelector(`#${host} input[value="${value}"]`);radio.checked=true;radio.dispatchEvent(new w.Event('change',{bubbles:true}));};choose('customFieldKind','counter');assert(add.disabled);choose('customFieldSize','half');assert(add.disabled);choose('customFieldRequired','required');assert(!add.disabled);assert.equal(w.document.querySelectorAll('#customFieldKind input:checked').length,1);add.click();assert.equal(cfg.property.custom_report_fields[2].kind,'counter');assert.equal(cfg.property.custom_report_fields[2].size,'half');assert.equal(cfg.property.custom_report_fields[2].required,true);assert.equal(w.testConfigs().e2.clock_in.length,0);w.testSync();assert.equal(w.testConfigs().e1.clock_in[0],'custom_second');dom.window.close();
 ({dom,w,html}=page('report.html','https://omgworks24.com/report.html?type=clock_in'));w.eval(read('work-config.js'));const fields=[{key:'custom_t',label:'Text',kind:'text',size:'half',required:true},{key:'custom_n',label:'Number',kind:'numeric',size:'half',required:false},{key:'custom_c',label:'Count',kind:'counter',size:'full',required:true},{key:'custom_r',label:'Rooms',kind:'rooms',size:'half',required:true},{key:'custom_p',label:'Photo',kind:'photo',size:'half',required:false}];const property={name:'Test',business_type:'lodging',room_types:[{name:'Room',rooms:['101']}],custom_report_fields:fields};const config={property,report_config:{clock_in:['custom_c','custom_t','custom_n','custom_r','custom_p'],reminder_cards:[]}};let sent;w.omgReport={ready:Promise.resolve({employeeName:'One',timezone:'Asia/Seoul'}),clockInText:()=>'',submit:async p=>sent=p};w.omgWorkConfig.load=async()=>config;w.OMGPhoto={dataURL:async()=> 'data:image/jpeg;base64,AAAA'};inline(w,html);await tick();assert.deepEqual(Array.from(w.document.querySelectorAll('.custom-result > .field-head h2'),n=>n.textContent),['Count *','Text *','Number','Rooms *','Photo']);assert.equal(w.document.querySelector('.custom-result .help'),null);assert(w.document.querySelector('#custom_t').parentNode.classList.contains('field-head'));assert(w.document.getElementById('custom_t').closest('.custom-result').classList.contains('half'));assert(w.document.getElementById('custom_c').closest('.custom-result').classList.contains('full'));const submit=()=>w.document.getElementById('reportForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));submit();await tick();assert.equal(sent,undefined);assert.match(w.document.getElementById('formMessage').textContent,/필수/);w.document.getElementById('custom_t').value='Clean';w.document.getElementById('custom_c').value='3';const room=w.document.querySelector('input[name="custom_r"]');room.checked=true;room.dispatchEvent(new w.Event('change',{bubbles:true}));submit();await tick();assert.equal(sent.custom_n,'');assert.equal(sent.custom_c,3);assert.equal(sent.custom_r[0],'101');assert.equal(sent.custom_p,'');assert.equal(sent.report_fields[0].key,'custom_c');dom.window.close();
 console.log('PASS: click order/removal/reselect, single kind requirement, employee isolation, inline five result types, typed ordered submission');
})().catch(e=>{console.error(e);process.exitCode=1;});
