package com.oneminute.guesthousemanager;
import android.app.*;import android.content.*;import android.graphics.Color;import android.media.*;import android.net.Uri;import android.os.*;import androidx.core.app.NotificationCompat;
public class EmergencyAlarmService extends Service {
 static final String CH="urgent_alerts"; MediaPlayer player; Vibrator vibrator;
 @Override public void onCreate(){super.onCreate();NotificationChannel c=new NotificationChannel(CH,"긴급 알림",NotificationManager.IMPORTANCE_HIGH);c.setDescription("확인할 때까지 울리는 긴급 알림");c.enableVibration(true);c.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);getSystemService(NotificationManager.class).createNotificationChannel(c);}
 @Override public int onStartCommand(Intent i,int f,int id){String alert=i.getStringExtra("alertId"),msg=i.getStringExtra("message"),mode=i.getStringExtra("mode");boolean test="test".equals(mode);Intent ack=new Intent(this,AcknowledgeReceiver.class);ack.putExtra("alertId",alert);PendingIntent pi=PendingIntent.getBroadcast(this,alert==null?0:alert.hashCode(),ack,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new NotificationCompat.Builder(this,CH).setSmallIcon(android.R.drawable.ic_dialog_alert).setColor(Color.RED).setContentTitle(test?"긴급알림 테스트":"사장님 긴급알림").setContentText(msg).setStyle(new NotificationCompat.BigTextStyle().bigText(msg)).setOngoing(!test).setPriority(NotificationCompat.PRIORITY_MAX).setCategory(NotificationCompat.CATEGORY_ALARM).addAction(0,"확인했습니다",pi).build();startForeground(9001,n);vibrator=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(test){vibrator.vibrate(VibrationEffect.createOneShot(1000,VibrationEffect.DEFAULT_AMPLITUDE));new Handler(Looper.getMainLooper()).postDelayed(this::stopSelf,1800);return START_NOT_STICKY;}Uri tone=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);player=MediaPlayer.create(this,tone);if(player!=null){player.setLooping(true);player.start();}vibrator.vibrate(VibrationEffect.createWaveform(new long[]{0,1000,600},0));return START_STICKY;}
 @Override public void onDestroy(){if(player!=null){player.stop();player.release();}if(vibrator!=null)vibrator.cancel();super.onDestroy();}
 @Override public android.os.IBinder onBind(Intent i){return null;}
}
