-- Isolated representative schema. No production records or session credentials.
create role anon; create role authenticated; create schema omg_private; create function omg_private.token_hash(uuid) returns text language sql immutable as 'select md5($1::text)';
create table public.attendance_adjustment_requests (id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,employee_id uuid,work_session_id uuid,original_clock_in_at timestamptz,original_clock_out_at timestamptz,requested_clock_in_at timestamptz,requested_clock_out_at timestamptz,status text default 'pending'::text,requested_at timestamptz default clock_timestamp(),approved_at timestamptz,approved_by uuid,rejected_at timestamptz,rejected_by uuid);
create table public.calendar_events (id uuid primary key default gen_random_uuid(),property_id uuid,creator_kind text,creator_employee_id uuid,owner_target bool default false,target_employee_ids uuid[] default '{}'::uuid[],title text,details text default ''::text,start_at timestamptz,end_at timestamptz,all_day bool default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.employees (id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,display_name text,pin_hash text,role text default 'staff'::text,active bool default true,created_at timestamptz default now(),login_failures int4 default 0,login_locked_until timestamptz,report_config jsonb default '{"clock_in": ["clean_rooms", "inspect_rooms", "no_show", "bedding_stain", "reminder_cards"], "clock_out": ["cleaned_rooms", "inspected_rooms"], "reminder_cards": [{"id": "watch", "text": "출근 즉시 워치 착용.\n절대 빼지 마세요. 방수임.\n게하폰과 5미터 이내에 있어야 작동합니다.", "image": "directive-watch.png", "title": "워치 착용", "weekdays": [0, 1, 2, 3, 4, 5, 6]}, {"id": "guest-guide", "text": "짐을 들어주고 문 앞까지 갈 것.\n도어락과 카드키 설명.\n앉아서 말로만 안내하는 건 퇴사 사유임.", "image": "directive-guest-guide.jpg", "title": "게스트 직접 안내", "weekdays": [0, 1, 2, 3, 4, 5, 6]}, {"id": "carry-devices", "text": "워치와 게하폰을 책상 위에 두고 청소하지 마세요.\n알람을 놓치지 않도록 근무 중 항상 몸에 소지합니다.", "image": "shiba-worker-logo-v2.png", "title": "게하폰·워치 항상 소지", "weekdays": [0, 1, 2, 3, 4, 5, 6]}, {"id": "final-check", "text": "객실을 나오기 전에 비품, 도어락, 조명, 냉난방 상태를 마지막으로 확인합니다.", "image": "shiba-cleaner-logo.png", "title": "객실 최종 확인", "weekdays": [0, 1, 2, 3, 4, 5, 6]}]}'::jsonb,scheduled_clock_in time,scheduled_clock_out time,lateness_threshold_minutes int4,profile_image text);
create table public.missions (id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,title text,description text default ''::text,timing text default 'today'::text,priority text default 'normal'::text,target_employee_ids jsonb default '[]'::jsonb,photo_required bool default false,estimated_minutes int4 default 30,due_at timestamptz,active bool default true,created_at timestamptz default now(),updated_at timestamptz default now(),creator_type text default 'owner'::text,creator_employee_id uuid,description_photo text default ''::text);
create table public.owner_sessions (id uuid primary key default gen_random_uuid(),owner_id uuid,business_id uuid,property_id uuid,login_token_hash text,token_expires_at timestamptz,created_at timestamptz default now());
create table public.owners (id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,display_name text,login_id text,pin_hash text,active bool default true,login_failures int4 default 0,login_locked_until timestamptz,created_at timestamptz default now(),profile_image text);
create table public.properties (id uuid primary key default gen_random_uuid(),business_id uuid,name text,code text,timezone text default 'Asia/Seoul'::text,created_at timestamptz default now(),rooms jsonb default '[]'::jsonb,room_types jsonb default '[]'::jsonb,management_number int4,notice text default ''::text,service_status text default 'trial'::text,trial_ends_at timestamptz,operator_note text default ''::text,status_updated_at timestamptz default clock_timestamp(),status_updated_by uuid,business_type text,custom_report_fields jsonb default '[]'::jsonb,clock_in_basis text default 'first_login'::text);
create table public.property_message_recipients (id uuid primary key default gen_random_uuid(),message_id uuid,recipient_key text,recipient_type text,owner_id uuid,employee_id uuid,read_at timestamptz,acknowledged_at timestamptz,acknowledged_name text);
create table public.property_messages (id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,sender_type text,sender_owner_id uuid,sender_employee_id uuid,message text,priority text default 'normal'::text,message_type text default 'general'::text,attendance_request_id uuid,created_at timestamptz default clock_timestamp(),property_share_request_id uuid,source text,external_message_id text);
create table public.property_share_requests (id uuid primary key default gen_random_uuid(),requester_property_id uuid,target_property_id uuid,requester_owner_id uuid,requested_permissions text[],status text default 'pending'::text,requested_at timestamptz default clock_timestamp(),approved_at timestamptz,approved_by uuid);
create table public.work_sessions (id uuid primary key default gen_random_uuid(),business_id uuid,property_id uuid,employee_id uuid,shift text,work_date date default ((now() AT TIME ZONE 'Asia/Seoul'::text))::date,clock_in_at timestamptz default now(),clock_out_at timestamptz,login_token_hash text,checkin_report_at timestamptz,checkout_report_at timestamptz,status text default 'working'::text,created_at timestamptz default now(),token_expires_at timestamptz default '-infinity'::timestamp with time zone,first_login_at timestamptz);
alter table property_messages add constraint property_messages_message_type_check check(message_type in ('general','emergency_report','attendance_approval','property_share_approval','announcement','attendance_warning'));
